- contribute/developer-guide/README.md
- contribute/developer-guide/attributes.yaml.sample
- contribute/developer-guide/generate_chart.py
- contribute/developer-guide/templates/chaoslib_tmpl
- contribute/developer-guide/templates/chartserviceversion.tmpl
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/experiment_custom_resource.tmpl
- contribute/developer-guide/templates/experiment_engine.tmpl
- contribute/developer-guide/templates/experiment_k8s_job.tmpl
- contribute/developer-guide/templates/experiment_rbac.tmpl
- contribute/developer-guide/templates/package.tmpl
- Adding scaffolded script to generate sample experiment
> feat(go-sdk): Adding scaffolded script to generate sample experiment

- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/pod-delete/README.md
- pkg/math/math.go
- Fixes: #7 
- Adding README and math utils in pod-delete
> feat(experiments): Adding README and math utils in pod-delete

- experiments/generic/pod-delete/README.md
- remove the unnecessary envs from readme
> update(readme): remove the unnecessary envs from readme

- contribute/developer-guide/templates/chaoslib_tmpl
- contribute/developer-guide/templates/experiment.tmpl
> update(scaffold): adding the events & logrus in the scaffold

- contribute/developer-guide/attributes.yaml.sample
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/experiment_custom_resource.tmpl
- go.mod
- Making the auxiliarychecks optional
> update(scoffold): Making the auxiliarychecks optional

- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/pod-delete/README.md
- experiments/generic/pod-delete/pod-delete-k8s-job.yml
- go.mod
- go.sum
- pkg/environment/environment.go
- pkg/status/application.go
-  Adding the force delete option in pod-delete
> update(pod-delete): adding the force delete option in pod-delete

- build/litmus-go/Dockerfile
Resolves issue #5
- Changed to Alpine Base Image, reduced the image size from 143M to 47M
Signed-off-by: Soumya Ghosh Dastidar <soumyaghosh.dastidar@mayadata.io>
> feat(image): Adding the lighter base image in the Dockerfile

- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/pod-delete/README.md
- experiments/generic/pod-delete/pod-delete.go
- pkg/environment/environment.go
- pkg/status/application.go
- pkg/types/types.go
- fixes: #4 
- Adding the support for the helper pod for pod-delete experiment
> feat(helper-pod): Adding support for pod-delete helper pod

- contribute/developer-guide/templates/experiment.tmpl
- Updating the events generation in scaffold
> update(scaffold): Updating the events generation in scaffold

- build/generate_go_binary
- go.mod
> feat(cpu-hog): generating binaries for cpu-hog experiment

- Makefile
- experiments/generic/cpu-hog/cpu-hog-k8s-job.yml
- experiments/generic/pod-delete/README.md
- experiments/generic/pod-delete/pod-delete-k8s-job.yml
> update(image): Updating the litmus-go image

- contribute/developer-guide/generate_chart.py
- contribute/developer-guide/templates/environment.tmpl
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/types.tmpl
- pkg/pod-cpu-hog/environment/environment.go
- updating contribution guide according to new schema changes
> update(contribution-guide): updating contribution guide according to new schema changes

- build/generate_go_binary
- build/litmus-go/Dockerfile
- chaoslib/litmus/node_drain/node-drain.go
- experiments/generic/node-drain/README.md
- experiments/generic/node-drain/node-drain-k8s-job.yml
- experiments/generic/node-drain/node-drain.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog-k8s-job.yml
- experiments/generic/pod-memory-hog/pod-memory-hog-k8s-job.yml
- experiments/generic/pod-network-corruption/pod-network-corruption-k8s-job.yml
- experiments/generic/pod-network-duplication/pod-network-duplication-k8s-job.yml
- experiments/generic/pod-network-latency/pod-network-latency-k8s-job.yml
- experiments/generic/pod-network-loss/pod-network-loss-k8s-job.yml
- go.mod
- go.sum
- pkg/generic/node-drain/environment/environment.go
- pkg/generic/node-drain/types/types.go
- fixes: litmuschaos/litmus#1666
> feat(node-drain): Adding the node drain experiment

- build/generate_go_binary
- chaoslib/litmus/node_memory_hog/node-memory-hog.go
- experiments/generic/node-memory-hog/node-memory-hog-k8s-job.yml
- experiments/generic/node-memory-hog/node-memory-hog.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/status/nodes.go
- Adding the node-memory-hog experiment
- fixes: litmuschaos/litmus#1671
> feat(node-memory-hog): Adding the node-memory-hog experiment

- build/generate_go_binary
- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill-k8s-job.yml
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/kubelet-service-kill/types/types.go
- pkg/status/nodes.go
- Adding the kubelet-service-kill experiment
- fixes: litmuschaos/litmus#1680
> feat(kubelet-service-kill): Adding the kubelet-service-kill experiment

- build/generate_go_binary
- chaoslib/litmus/node_taint/node-taint.go
- experiments/generic/node-taint/README.md
- experiments/generic/node-taint/node-taint-k8s-job.yml
- experiments/generic/node-taint/node-taint.go
- pkg/generic/node-taint/environment/environment.go
- pkg/generic/node-taint/types/types.go
- fixes: litmuschaos/litmus#1667
> feat(node-taint): Adding the node taint experiment

- build/generate_go_binary
- chaoslib/litmus/container_kill/container-kill.go
- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
- chaoslib/litmus/node_memory_hog/node-memory-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- chaoslib/pumba/container_kill/container-kill.go
- experiments/generic/container-kill/container-kill-k8s-job.yml
- experiments/generic/container-kill/container-kill.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- Adding the container-kill experiment
- fixes: litmuschaos/litmus#1700
> feat(container-kill): Adding the container-kill experiment

- contribute/developer-guide/templates/experiment.tmpl
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/types/types.go
- fix: litmuschaos/litmus#1724
> fix(chaos-result): fixing failed verdict update in chaos result

- contribute/developer-guide/templates/experiment.tmpl
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/types/types.go
-  It consists of the following commits:
- c87227e56535574e18d3aef9cbb5a13643eafd51
> feat(1.6.0): Cherry-pick for 1.6.0

- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill-k8s-job.yml
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/kubelet-service-kill/types/types.go
> feat(kubelet-service-kill): Adding ability to pass nodeName explictly in kubelet-service-kill

- chaoslib/litmus/container_kill/container-kill.go
- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
- chaoslib/litmus/node_memory_hog/node-memory-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- chaoslib/pumba/network_chaos/network-chaos.go
- pkg/status/application.go
> feat(go-experiments): Updating failure condition for helper pod

- chaoslib/litmus/container_kill/container-kill.go
- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
- chaoslib/litmus/node_memory_hog/node-memory-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- chaoslib/pumba/network_chaos/network-chaos.go
- pkg/result/chaosresult.go
- pkg/status/application.go
fixes: litmuschaos/litmus#1474
> feat(istio): Adding support to run in istio enabled mode

- chaoslib/litmus/container_kill/container-kill.go
- chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.go
- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
- chaoslib/litmus/node_memory_hog/node-memory-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- chaoslib/pumba/network_chaos/network-chaos.go
- experiments/generic/pod-network-corruption/pod-network-corruption-k8s-job.yml
- experiments/generic/pod-network-duplication/pod-network-duplication-k8s-job.yml
- experiments/generic/pod-network-latency/pod-network-latency-k8s-job.yml
- experiments/generic/pod-network-loss/pod-network-loss-k8s-job.yml
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/result/chaosresult.go
- pkg/status/application.go
It consists of follwing commits:
- 09b85a7513ecca2418fec1ab631c5d07a301de52
- 8a861ead3e2857516696e2e42aa1865ab1ec596a
> [CherryPick for 1.6.1]

- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
> update(node-cpu-hog): Adding the command field for node-cpu-hog helper

- chaoslib/litmus/node_cpu_hog/node-cpu-hog.go
- 7ada19395dcc64938eb0990bd50a66e9f487c2e8
> [Cherry-pick for 1.6.2] 

- contribute/developer-guide/templates/experiment.tmpl
- sync the experiment template to new schema changes for the summary events
> update(sdk): sync the experiment template with new schema

- contribute/developer-guide/README.md
> (fix)contrib: fix dev guide formatting

- contribute/developer-guide/templates/experiment.tmpl
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-drain/environment/environment.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-taint/environment/environment.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-memory-hog/environment/environment.go
> chore(probe): Adding probes in all go experiments

- pkg/result/chaosresult.go
- Don't patch the probe score in result, if probes not defined!
> update(chaosresult): updating the chaosresult for probe score

- chaoslib/litmus/pod_autoscaler/pod-autoscaler.go
> refactor(pod-autoscaler): refactor the pod-scaler experiment

- build/litmus-go/Dockerfile
A GitLab CI run with the dockerfile changes:
- https://gitlab.mayadata.io/litmuschaos/litmus-e2e/pipelines/12501
> chore(Dockerfile): Add user_id in the dockerfile

- contribute/developer-guide/templates/experiment.tmpl
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- Makes the pre/post chaos events more meaningful (fixes an issue where probe success is mentioned even if probes are not defined)
> fix(events): fixing the event msg for pre/post chaos checks

- chaoslib/litmus/disk_fill/disk-fill.go
> refactor(disk-fill): Removing privileged mode in disk-fill helper pod

- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
> fix(experiment): fix the pod-cpu/memory-hog experiments

- chaoslib/pumba/network-chaos/lib/network-chaos.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
https://github.com/litmuschaos/litmus/issues/1488#issue-614146928
> Support specifying target with pumba lib while performing network chaos

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/kubelet-service-kill/types/types.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/utils/common/common.go
- fixes: https://github.com/litmuschaos/litmus/issues/1973
- This PR is for passing the annotation from chaos pod to helper pod.
> feat(annotations): Pass Annotations to helper pod from chaos pod

- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- pkg/utils/common/common.go
> chore(appinfo): Add ability to run experiments with optional appinfo

- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-memory-hog/types/types.go
> chore(node-name): Adding ability to provide explicit node name

- build/generate_go_binary
- build/litmus-go/Dockerfile
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/network_latency/cri/crictl.go
- chaoslib/litmus/network_latency/cri/crictl_test.go
- experiments/generic/network-latency/network-latency.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- go.sum
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/network-latency/environment/environment.go
> feat(network-chaos): Adding support for containerd/crio in network-chaos

- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- pkg/types/types.go
> chore(abort-event): Adding abort events for network-chaos

- build/litmus-go/Dockerfile
> fix(dockerfile): Add a non root user to run the process in Dockerfile

- build/litmus-go/Dockerfile
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/types/types.go
commits:
- fc550fa9ffd1c8c3b3a0a3cb40b3c894c494455f
- 2b1bf308c9de7248f144824c62c1290a18627525
- a51ded441a442cbd916fd8dddce96baebe5c37ac
> [Cherry Pick for 1.8.0]

- Makefile
- Update the image tags for dev branch 
> (chore)build: update image tags for the dev branch

- Makefile
- build/push
> Minor Fix/Add correct push command for multi-arch

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- experiments/generic/container-kill/test/test.yml
- experiments/generic/pod-network-corruption/test/test.yml
- experiments/generic/pod-network-duplication/test/test.yml
- experiments/generic/pod-network-latency/test/test.yml
- experiments/generic/pod-network-loss/test/test.yml
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- correcting the socket path env name to `SOCKET_PATH` and update test.yaml.
> chore(socketPath): correcting the socketPath env name

- build/litmus-go/Dockerfile
> fix(permission-issue): fixing the username permission issue for sockfile

- build/litmus-go/Dockerfile
> fix/ Add permission for network experiments for multiarch

- build/litmus-go/Dockerfile
> fix(userid): revert the userid from dockerfile

- chaoslib/pumba/network-chaos/lib/duplication/duplication.go
> fix(duplicate): fixing network duplicate exp

- chaoslib/litmus/network-chaos/lib/corruption/corruption.go
- chaoslib/litmus/network-chaos/lib/duplication/duplication.go
- chaoslib/litmus/network-chaos/lib/latency/latency.go
- chaoslib/litmus/network-chaos/lib/loss/loss.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/pumba/network-chaos/lib/latency/latency.go
- chaoslib/pumba/network-chaos/lib/loss/loss.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
> chore(network-chaos): splitting network chaos for containerd

- chaoslib/pumba/network-chaos/lib/network-chaos.go
- 273ab011770f190d2e532f0a8332aae64f917339
> [Cheerypick for 1.8.x]

- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/network-latency/network-latency.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-io-stress/node-io-stress.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-io-stress/pod-io-stress.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- Removing the unnecessary event from all the experiments.
> refactor(events): removing unnecessary event

- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
> chore(ipfilter): Adding ipfilter in network chaos for containerd/crio

- chaoslib/litmus/container-kill/lib/container-kill.go
> (fix)containerKill: Fix the container kill experiment for containerd runtime

- .github/workflows/guide.md
- .github/workflows/main.yml
- README.md
- This PR is adding a custom e2e bot to test a particular PR on commit level. This can be done by commenting on a PR in this formate: 
`/run-e2e-<test-name/test-group-name>`
Different tests name and test groups names are used to run the e2e. Get more details about this in the [bot guide](https://github.com/uditgaurav/litmus-go/blob/master-add-actions/.github/workflows/guide.md)
_Experiments Added_
| Resource chaos | Network Chaos | IO Chaos | Others |
|-----------------------|-----------------------|--------------|-----------|
| pod-cpu-hog       | pod-network-latency| node-io-stress| pod-delete |
| pod-memory-hog| pod-network-loss     |                     | container-kill |
| node-cpu-hog      | pod-network-corruption|              | …
> chore(actions): Add GitHub action custom test to test a particular PR

- .travis.yml
- Makefile
- This PR includes the addition of trivy check.
_Other Checks_
- Formatting, linting, and check unused packages check is also added.
> chore(checks): Add Docker Security Checks and some formatting checks  

- .github/workflows/main.yml
> (chore)action: Fix the actions for merge

- chaoslib/litmus/network-chaos/lib/network-chaos.go
> fix(network-chaos): Make targetips optional if target_host defined

- pkg/result/chaosresult.go
- updating probes status in abort case
> chore(probe): updating probes status in abort case

- .travis.yml
- Travis is unable to fetch the version of trivy sometimes because of which it gets fail. So updated the URL with the latest trivy version.
> fix(travis): Add travis fix

- contribute/developer-guide/templates/experiment_rbac.tmpl
- experiments/cassandra/pod-delete/rbac.yaml
- experiments/generic/container-kill/rbac.yaml
- experiments/generic/disk-fill/rbac.yaml
- experiments/generic/kubelet-service-kill/rbac.yaml
- experiments/generic/network-latency/rbac.yaml
- experiments/generic/node-cpu-hog/rbac.yaml
- experiments/generic/node-drain/rbac.yaml
- experiments/generic/node-io-stress/rbac.yaml
- experiments/generic/node-memory-hog/rbac.yaml
- experiments/generic/node-taint/rbac.yaml
- experiments/generic/pod-autoscaler/rbac.yaml
- experiments/generic/pod-cpu-hog/rbac.yaml
- experiments/generic/pod-delete/rbac.yaml
- experiments/generic/pod-io-stress/rbac.yaml
- experiments/generic/pod-memory-hog/rbac.yaml
- experiments/generic/pod-network-corruption/rbac.yaml
- experiments/generic/pod-network-duplication/rbac.yaml
- experiments/generic/pod-network-latency/rbac.yaml
- experiments/generic/pod-network-loss/rbac.yaml
Update CR versions to prevent warning message, resolves https://github.com/litmuschaos/litmus/issues/1963
> fix: update CRs

- chaoslib/litmus/container-kill/helper/crictl.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/result/chaosresult.go
- pkg/status/application.go
- pkg/utils/common/common.go
> refactor(log): updating the error message

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/utils/common/common.go
> chore(skip-chaos-pods): ignore chaos-pod to be targeted if appLabels are empty

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/powerfulseal/pod-delete/lib/pod-delete.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/result/chaosresult.go
> chore(chaos_result): Add ChaosPod label to ChaosResult

- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
> chore(probe-chain): Adding probe chaining in http & k8s probe

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/result/chaosresult.go
> chore(labels): skip the labels addition

- contribute/developer-guide/generate_experiment.go
- contribute/developer-guide/templates/environment.tmpl
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/experiment_engine.tmpl
- contribute/developer-guide/templates/types.tmpl
> chore(litmus-sdk): update the litmus-sdk to latest schema changes

- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
Issue
- fixes: https://github.com/litmuschaos/litmus-go/issues/176
> fix(node-io-stress): Add fix for node-io-stress

- pkg/result/chaosresult.go
> fix(abort): fixing the result updation for abort

- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-drain/experiment/node-drain.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-taint/experiment/node-taint.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
> refactor(experiment): handle probe initialization errors in experiments

- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-drain/experiment/node-drain.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-taint/experiment/node-taint.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- pkg/result/chaosresult.go
It consists following commits:
- b9882cfcde80361e16570f56268f1d7f6b34660d
- f471aa60c3cf9d1d90c0aad1ef213133381e9bd4
- b88e93ffc45282f2cc7d9520a4635c08c775c75f
> [Cherry-Pick for v1.9.0]

- .github/CODEOWNERS
> chore(codeowners): Add codeowners of litmus-go

- pkg/events/event.go
> chore(events): Adding unique event name for multiple experiment in engine

- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/pod-io-stress/environment/environment.go
- pkg/generic/pod-io-stress/types/types.go
> chore(pod-io-stress): Add support for volume mount path for pod-io-stress experiment

- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- fixes: https://github.com/litmuschaos/litmus-go/issues/83 && https://github.com/litmuschaos/litmus/issues/2145
- Adding abort in pod autoscaling experiment.
> feat(abort): Add abort in pod autoscaler experiment

- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- Adding support for statefulset resource type
> chore(autoscaler): Adding support for statefulset resource type

- chaoslib/litmus/ebs-loss/lib/ebs-loss.go
- chaoslib/litmus/ec2-terminate/lib/ec2-terminate.go
- experiments/kube-aws/ebs-loss/experiment/ebs-loss.go
- experiments/kube-aws/ec2-terminate/experiment/ec2-terminate.go
- pkg/cloud/aws/aws-configure.go
- pkg/cloud/aws/ec2-instance-status.go
- pkg/status/application.go
- pkg/status/nodes.go
- pkg/utils/exec/exec.go
> chore(logs): improve the logging of go-runner

- pkg/generic/network-chaos/environment/environment.go
> chore(TARGET_IPS): modified the TARGET_IPs env

- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- contribute/developer-guide/templates/experiment.tmpl
- experiments/cassandra/pod-delete/experiment/pod-delete.go
- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-drain/experiment/node-drain.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-restart/experiment/node-restart.go
- experiments/generic/node-taint/experiment/node-taint.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
- experiments/kube-aws/ebs-loss/experiment/ebs-loss.go
- experiments/kube-aws/ec2-terminate/experiment/ec2-terminate.go
> chore(logs): improve the experiment logs

- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
> chore(probe): restructured the probe schema/code

- chaoslib/litmus/ebs-loss/lib/ebs-loss.go
- pkg/cloud/aws/aws-ebs-status.go
- Update the status check for detaching and attaching the ebs volume to the ec2 instance.
> Enhance(ebs): Update the status check for attaching/detaching the EBS Volume

- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-restart/experiment/node-restart.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-io-stress/environment/environment.go
- pkg/generic/node-io-stress/types/types.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/status/nodes.go
- pkg/utils/common/common.go
> chore(target-nodes): Add an ability to provide multiple target-nodes

- build/litmus-go/Dockerfile
> chore(update): Update Dockerfile for litmus-go

- .travis.yml
- Makefile
- build/generate_go_binary
- build/go-multiarch-build.sh
- build/litmus-go/Dockerfile
- build/push
> chore(add): Add multiarch image into master

- .travis.yml
- Makefile
- build/generate_go_binary
- build/go-multiarch-build.sh
- build/litmus-go/Dockerfile
- build/push
- chaoslib/litmus/node-restart/lib/node-restart.go
- experiments/generic/node-restart/experiment/node-restart.go
- pkg/generic/node-restart/environment/environment.go
https://github.com/litmuschaos/litmus-go/commit/96c5de2d801bce134606fe5215bc248c25abc664
https://github.com/litmuschaos/litmus-go/commit/a4b5e6e8bc8b96379902621b7e5464f7ae52e4b3
> [Cherry-pick for v1.10.x]

- build/push
> chore(fix): Add fix for image push script

- build/push
https://github.com/litmuschaos/litmus-go/pull/209/commits/0922f5a19210202be9a15c6143c924f102c04d1d
> [Cherry-pick for 1.10.0 (ci fix)]

- pkg/result/chaosresult.go
> chore(probe): Add probeSuccessPercentage field as mandatory

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-io-stress/environment/environment.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-restart/environment/environment.go
- pkg/generic/pod-io-stress/environment/environment.go
- pkg/types/types.go
- pkg/utils/common/pods.go
> chore(jobcleanup): Delete the helper pod based on jobCleanupPolicy

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/kubelet-service-kill/types/types.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-io-stress/types/types.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/generic/node-restart/types/types.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-io-stress/types/types.go
- pkg/generic/pod-memory-hog/types/types.go
- pkg/utils/common/pods.go
- Propagating the resource requirements from the experiment pod to the helper pod.
> chore(resources): Adding resource requirements for helper pod

- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/promProbe.go
> chore(probe): enhancing the logs in probes

- pkg/events/event.go
- fixing chaosresult events generation for every run if re-run via same chaosengine
> chore(events): updating the chaosresult events

- contribute/developer-guide/README.md
- contribute/developer-guide/templates/experiment.tmpl
> chore(sdk): updating the scaffold files

- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/network-chaos/environment/environment.go
- Addind dynamic socketPath for the pumba helper pod.
- updated socketPath to docker socket path
> chore(pumba): Adding dynamic socketPath pumba helper

- Makefile
> Fix: Non root image build

- .travis.yml
> Remove: Remove trivy from dev

- Makefile
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-io-stress/environment/environment.go
- pkg/generic/pod-io-stress/types/types.go
- pkg/generic/pod-memory-hog/environment/environment.go
- pkg/generic/pod-memory-hog/types/types.go
- Add dynamic socket path for pod cpu,memory and io experiment.
- Refactor Makefile.
> chore(enhanc): Make socket path tunable from ENV and refactor Makefile

- Makefile
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-io-stress/environment/environment.go
- pkg/generic/pod-io-stress/types/types.go
- pkg/generic/pod-memory-hog/environment/environment.go
- pkg/generic/pod-memory-hog/types/types.go
Commit:
- a8834750083e8f27033746fcd7ff98a558bf55a1
> Cherry Pick for 1.11.1

- .github/workflows/run-e2e-on-new-pr.yml
- .github/workflows/run-e2e-on-pr-comment.yml
> chore(actions): Fix GitHub actions e2e for litmus-go

- pkg/events/event.go
> chore(events): update source and msg in engine events

- chaoslib/litmus/node-restart/lib/node-restart.go
- pkg/status/application.go
This PR changes the condtion of waiting for pod status, so it wait also
for the succeed state, because it may happen if the experiment is too
quick, that the helper pod is already finished. So the waiting will
timeout for waiting for the running state.
Signed-off-by: Ondra Machacek <omachace@redhat.com>
> Check also for succeded state of helper pod

- .github/workflows/release.yml
> Fix(actions): Fix Release build

- pkg/status/application.go
> (refactor)status checks: add expected app/pod state to log

- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- pkg/generic/pod-cpu-hog/environment/environment.go
-  Adding cpu-cores in pod-cpu-hog experiments
> chore(cpu-cores): Adding cpu-cores in pod-cpu-hog experiments

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> chore(logs): logging application details in chaoslib

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/network-chaos/helper/netem.go
> chore(host): Adding host in docker cli command

- contribute/developer-guide/README.md
- contribute/developer-guide/attributes.yaml.sample
- contribute/developer-guide/templates/chaoslib.tmpl
- contribute/developer-guide/templates/environment.tmpl
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/types.tmpl
> chore(sdk): updating the chaoslib template for the sdk

- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> Chore(fix): Fix disk and io experiments for nonroot

- .github/workflows/build.yml
- .github/workflows/push.yml
- .github/workflows/run-e2e-on-new-pr.yml
- Makefile
- build/generate_go_binary
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
> chore(dev): updating image tag to revert

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/utils/common/pods.go
- updating the helper labels in all the experiments
> feat(labels): updating the helper labels

- .github/workflows/run-e2e-on-new-pr.yml
- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- Adding support for different signals in container-kill tuned via ENV
> chore(container-kill): Adding support for different signals

- contribute/developer-guide/generate_experiment.go
- contribute/developer-guide/templates/category_chartserviceversion.tmpl
- contribute/developer-guide/templates/experiment.tmpl
- contribute/developer-guide/templates/experiment_chartserviceversion.tmpl
- contribute/developer-guide/templates/experiment_custom_resource.tmpl
- contribute/developer-guide/templates/experiment_k8s_deployment.tmpl
- contribute/developer-guide/templates/package.tmpl
> update(sdk): updating the sdk scaffold

- .github/workflows/run-e2e-on-new-pr.yml
- build/Dockerfile
- Added two tests along with pod affected percentage 100:
- Pod_Level_In_Series_Mode
- Pod_Level_In_Parallel_Mode
The tests are picked from the litmus-e2e repository.
The cluster used is `k3s` with docker runtime. 
Tested run serial mode - https://github.com/uditgaurav/test-litmus-go/pull/1/checks?check_run_id=1810127149
Tested run parallel mode - https://github.com/uditgaurav/test-litmus-go/pull/1/checks?check_run_id=1810278967
> Chore(e2e): Add some e2e tests on PR

- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
> chore(abort): updating termination grace period

- .github/workflows/build.yml
- .github/workflows/push.yml
- Makefile
- build/push
- Update docker buildx command and remove `sudo` in the push script to fix the broken CI.
> fix(CI): Fix buildx for 1.12.x branch

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- Adding the signal option for the docker, containerd and crio runtimes
> chore(signal): Adding signal in container-kill

- .github/workflows/build.yml
- .github/workflows/push.yml
- Makefile
- build/push
- This PR is for adding a new ci tag for `v1.11.x` branch from which we can make new patch releases on top of 1.11 release.
> Add a new image tag for v1.11.x branch

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- Erroring out the cases where neither the appLabel provided nor the TARGET_PODS defined and the annotationCheck is provided as false
> chore(applabels): Erroring out if applabel is not provided and annotationCheck is provided as false

- .github/workflows/run-e2e-on-new-pr.yml
- .github/workflows/run-e2e-on-pr-comment.yml
- Updating GitHub Chaos Actions to litmuschaos.
> Chore(actions): Update GitHub Chaos Actions

- bin/go-runner.go
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- contribute/developer-guide/templates/experiment.tmpl
- experiments/cassandra/pod-delete/experiment/pod-delete.go
- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-drain/experiment/node-drain.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-restart/experiment/node-restart.go
- experiments/generic/node-taint/experiment/node-taint.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-dns-chaos/experiment/pod-dns-chaos.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
- experiments/kube-aws/ebs-loss/experiment/ebs-loss.go
- experiments/kube-aws/ec2-terminate/experiment/ec2-terminate.go
- modifying the Fatal to Error in all the experiment as Fatal relaunch the experiment pod again and again
> fix(logging): modifying the Fatal to Error

- chaoslib/litmus/node-restart/lib/node-restart.go
> chore(node-restart): updating the node-restart experiment

- bin/go-runner.go
- chaoslib/litmus/vm-poweroff/lib/vm-poweroff.go
- experiments/vmware/vm-poweroff/README.md
- experiments/vmware/vm-poweroff/experiment/vm-poweroff.go
- experiments/vmware/vm-poweroff/test/test.yml
- pkg/cloud/vmware/get-vcenter-cookie.go
- pkg/cloud/vmware/start-vm.go
- pkg/cloud/vmware/stop-vm.go
- pkg/cloud/vmware/vm-status.go
- pkg/vmware/vm-poweroff/environment/environment.go
- pkg/vmware/vm-poweroff/types/types.go
- Adding VMWare PowerOff Experiment
- This experiment PowerOffs give VMWare VM Instance for a certain chaos duration before bringing it back to running state.
Signed-off-by: DelphineJoyneer <golkonda.joyneer@wipro.com>
> Core(New_exp): Adding VMWare VMPowerOff Experiment

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- Enhancing the pod autoscaler experiment logging.
- Add helper keyword in the helper pod name.
- Replacer Available Replica to Ready Replica in the check.
> Chore(update): Enhance pod-autoscaler logs and update helper pod name

- chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
- adding spoofmap env in helper pod
> chore(dns): adding spoofmap env in helper pod

- pkg/kafka/environment/environment.go
> Fix sequence env in kafka broker pod experiment

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Adding contribution guide
- Adding Issue template
- Adding Pull request tempalate
> chore(contribution): Adding contribution guide, issue & PR templates

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- pkg/utils/common/common.go
updating the env setter function for the helper pod
> chore(env): : updating the env setter function for the helper pods

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- Adding statusCheckTimeouts for the helper status check
**Checklist:**
-   [x] E2E run Required for …
> chore(helper): Adding statusCheckTimeouts for the helper status check

- pkg/probe/comparator/string.go
- fixed the comparator logs 
**Checklist:**
> fix(log): fixed the comparator logs

- chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
> Fix: Populate total chaos duration to helper in dns experiments

- chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
- pkg/probe/comparator/string.go
- pkg/result/chaosresult.go
- pkg/utils/annotation/annotation.go
It consists of following commits:
- 402a4687dc4cf5f561899204682482aff87ea352
- 090049152a4435e2964762ded3dbe69211643b6a
- d45c8d701d9032594d120f03d75b058148d1dba8
**Checklist:** …
> [Cherrypick for 1.13.7]

- experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
- experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
- Removing duplicate function calls, which may create multiple stopped events and create the result update conflicts for the abort cases
**Checklist:** …
> fix(ec2): removing the duplicate function calls

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/helper/disk-fill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- Adding experiment name & instance-id inside helper pods for the cases:
- when experiment-name is different from default exp-name then the helper pod misinterprets the result name as it is using default experiment name.
- adding instance-id inside helper pods
**Checklist:**
-   [ ] …
> (result): adding experiment & instance-id inside helper pod

- .github/workflows/run-e2e-on-pr-commits.yml
> chore(e2e): commenting helm-e2e workflow

- pkg/probe/cmdprobe.go
Passing experiment serviceAccount to probe pod(required for the command probe with source image)
**Checklist:** …
> chore(probe): passing experiment serviceAccount to the probe pod

- go.mod
- go.sum
> update(version): updating kubernetes version

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/docker-service-kill/lib/docker-service-kill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/docker-service-kill/types/types.go
- pkg/generic/kubelet-service-kill/types/types.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-io-stress/types/types.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/generic/node-restart/types/types.go
- pkg/generic/pod-dns-chaos/types/types.go
- pkg/generic/stress-chaos/types/types.go
- pkg/types/types.go
- pkg/utils/common/pods.go
> chore(labels): passing labels to the helper pod

- pkg/generic/stress-chaos/environment/environment.go
- Fix stress chaos with pumba lib with updated pumba
**Checklist:**
> Fix stress chaos with pumba lib with updated pumba

- pkg/probe/probe.go
> chore(retry): adding retries for the kubeapi request

- chaoslib/litmus/pod-fio-stress/lib/pod-fio-stress.go
Signed-off-by: neelanjan00 <neelanjan@chaosnative.com>
**What this PR does / why we need it**: Corrects spelling errors in the various files
> Spell Check Corrections

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
> Chore(stress-chaos): Remove the stress process on timeout without failure

- build/Dockerfile
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- contribute/developer-guide/README.md
- contribute/developer-guide/templates/experiment.tmpl
- pkg/status/nodes.go
Commits are:
- f2db46f74ae8cd3f99a62e6d69ee4b7f28ba8563
- 07c6647006598a98d435b2b9b6193853692747c2
- 8b962d41d8792edd963cd644d68ce5913b8b43d5
> [ Cherry-pick for 2.4.0 ]

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- pkg/generic/stress-chaos/environment/environment.go
- pkg/generic/stress-chaos/types/types.go
> Chore(stress-chaos): Support stress-chaos experiment with custom experiment name

- chaoslib/litmus/network-chaos/lib/latency/latency.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
> Chore(network-chaos): Add jitter in pod-network-latency experiment

- .github/workflows/build.yml
- go.mod
-  Fix snyk security scan on litmus-go
**Checklist:**
> Chore(snyk): Fixes snyk security scan on litmus-go

- chaoslib/litmus/network-chaos/lib/corruption/corruption.go
- chaoslib/litmus/network-chaos/lib/duplication/duplication.go
- chaoslib/litmus/network-chaos/lib/loss/loss.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/pumba/network-chaos/lib/corruption/corruption.go
- chaoslib/pumba/network-chaos/lib/duplication/duplication.go
- chaoslib/pumba/network-chaos/lib/loss/loss.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/utils/common/common.go
> Chore(network-chaos): Randomize Chaos Tunables for Netowork Chaos Experiment

- contribute/developer-guide/templates/experiment.tmpl
Signed-off-by: shubhamc <shubhamc@jfrog.com>
**Checklist:**
> update(sdk): updating litmus sdk for the defaultAppHealthCheck

- .github/workflows/release.yml
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
Fixes release workflow trigger to only run on tag creation, refer [issue](https://github.com/actions/runner/issues/1007)
> fix: updated release workflow trigger

- pkg/status/nodes.go
Signed-off-by: Akash Shrivastava <akash@chaosnative.com>
Fixes the issue when an incorrect node name is provided. The current implementation doesn't return an error in the node status check, this PR fixes that by returning an error in the node status check if the node does not exists
**Checklist:**
> Incorrect node name error fix

- .github/workflows/run-e2e-on-pr-commits.yml
- chaoslib/litmus/http-chaos/lib/http-chaos.go
- Fix node level e2e-pipeline to run the ci tests on PR
**Checklist:**
> Fix node level e2e-pipeline to run the ci tests on PR

- .github/workflows/run-e2e-on-pr-commits.yml
- pkg/cloud/gcp/vm-operations.go
> Fix(pipeline): Fixes e2e pipeline check

- go.mod
- go.sum
- pkg/result/chaosresult.go
> chore(history): Converting history field to pointer

- contribute/developer-guide/templates/chaoslib_helper.tmpl
- contribute/developer-guide/templates/environment_helper.tmpl
- contribute/developer-guide/templates/types_helper.tmpl
> chore(sdk): Adding service account and helper pod failure check

- pkg/status/application.go
> chore(status): Handling terminated containers

- .github/workflows/run-e2e-on-pr-commits.yml
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- Since we are using the root user we don't need any extra capability in the helper pod.
**Checklist:**
-   [ ] …
> Chore(capability): Remove extra capabilities from stress chaos experiments

- chaoslib/litmus/network-chaos/helper/netem.go
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
I have added a break statement to break the execution of the loop once a duplicate IP is found.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #561
**Checklist:**
-   [x] Fixes #561 
-   [ ] …
> Optimized the logic for duplicate IP check

- pkg/status/nodes.go
**What this PR does / why we need it**: To fix kubelet service kill experiment error.
https://github.com/litmuschaos/litmus-go/issues/536
**Checklist:**
> Fix helper pod issue for Kubelet Experiment

- chaoslib/litmus/aws-ssm-chaos/lib/ssm-chaos.go
- experiments/aws-ssm/aws-ssm-chaos-by-id/experiment/aws-ssm-chaos-by-id.go
- experiments/aws-ssm/aws-ssm-chaos-by-tag/experiment/aws-ssm-chaos-by-tag.go
- experiments/azure/azure-disk-loss/experiment/azure-disk-loss.go
- experiments/azure/instance-stop/experiment/azure-instance-stop.go
- experiments/kube-aws/ebs-loss-by-id/experiment/ebs-loss-by-id.go
- experiments/kube-aws/ebs-loss-by-tag/experiment/ebs-loss-by-tag.go
- experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
- experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
> Health Check changes for AWS and Azure experiments

- experiments/gcp/gcp-vm-disk-loss-by-label/experiment/gcp-vm-disk-loss-by-label.go
- experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
- experiments/gcp/gcp-vm-instance-stop-by-label/experiment/gcp-vm-instance-stop-by-label.go
- experiments/gcp/gcp-vm-instance-stop/experiment/gcp-vm-instance-stop.go
Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>
**What this PR does / why we need it**: Adds pre-chaos and post-chaos status logs for GCP experiments
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #582
**Checklist:**
> fix(Experiment): Add status logs for GCP experiments

- build/Dockerfile
> chore(sudo): fixing sudo command error

- chaoslib/litmus/azure-disk-loss/lib/azure-disk-loss.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- go.mod
- go.sum
- pkg/clients/clientset.go
- pkg/probe/k8sprobe.go
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds k8s resource filtering based on resource names for the k8s probe.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes #599 
**Checklist:**
-   [x] PR messages has document related information
-   [ …
> feat: add resource name filtering in k8s probe

- go.mod
- go.sum
> chore(mod): updating go mod operator modules

- experiments/generic/node-drain/experiment/node-drain.go
- pkg/utils/common/pods.go
> fix(fmt): fixing fmt lint

- experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
- experiments/spring-boot/spring-boot-app-kill/experiment/spring-boot-app-kill.go
- experiments/spring-boot/spring-boot-cpu-stress/experiment/spring-boot-cpu-stress.go
- experiments/spring-boot/spring-boot-exceptions/experiment/spring-boot-exceptions.go
- experiments/spring-boot/spring-boot-memory-stress/experiment/spring-boot-memory-stress.go
> fix(experiment): fixing spring boot experiments

- pkg/spring-boot/spring-boot-chaos/environment/environment.go
> chore(spring-boot): simplifying spring boot experiments env

- chaoslib/litmus/pod-delete/lib/pod-delete.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- go.mod
- go.sum
- pkg/cerrors/custom_errors.go
- pkg/cerrors/errors.go
- pkg/probe/probe.go
- pkg/result/chaosresult.go
- pkg/status/application.go
- pkg/types/types.go
- pkg/utils/common/common.go
- pkg/utils/common/pods.go
- pkg/workloads/workloads.go
> feat(failstep): Improvised the failstep for pod-delete experiment

- chaoslib/litmus/vm-poweroff/lib/vm-poweroff.go
- experiments/vmware/vm-poweroff/experiment/vm-poweroff.go
- pkg/cerrors/custom_errors.go
- pkg/cloud/vmware/get-vcenter-cookie.go
- pkg/cloud/vmware/vm-operations.go
- pkg/cloud/vmware/vm-status.go
- pkg/vmware/vm-poweroff/environment/environment.go
- pkg/vmware/vm-poweroff/types/types.go
This PR updates the fail-step and error messages for the following VMware experiment
1. vm-poweroff
**Checklist:**
> Chore(Fail-Steps): Updated fail-step and error messages for VMware experiments

- chaoslib/litmus/aws-ssm-chaos/lib/ssm-chaos.go
- chaoslib/litmus/aws-ssm-chaos/lib/ssm/aws-ssm-chaos-by-id.go
- chaoslib/litmus/aws-ssm-chaos/lib/ssm/aws-ssm-chaos-by-tag.go
- chaoslib/litmus/ebs-loss/lib/ebs-loss-by-id/lib/ebs-loss-by-id.go
- chaoslib/litmus/ebs-loss/lib/ebs-loss-by-tag/lib/ebs-loss-by-tag.go
- chaoslib/litmus/ebs-loss/lib/ebs-loss.go
- chaoslib/litmus/ec2-terminate-by-id/lib/ec2-terminate-by-id.go
- chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
- experiments/aws-ssm/aws-ssm-chaos-by-id/experiment/aws-ssm-chaos-by-id.go
- experiments/aws-ssm/aws-ssm-chaos-by-tag/experiment/aws-ssm-chaos-by-tag.go
- experiments/kube-aws/ebs-loss-by-id/experiment/ebs-loss-by-id.go
- experiments/kube-aws/ebs-loss-by-tag/experiment/ebs-loss-by-tag.go
- experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
- experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
- pkg/aws-ssm/aws-ssm-chaos/environment/environment.go
- pkg/aws-ssm/aws-ssm-chaos/types/types.go
- pkg/cerrors/custom_errors.go
- pkg/cloud/aws/ebs/ebs-operations.go
- pkg/cloud/aws/ebs/ebs-volume-state.go
- pkg/cloud/aws/ec2/ec2-instance-status.go
- pkg/cloud/aws/ec2/ec2-operations.go
- pkg/cloud/aws/ssm/ssm-documentation.go
- pkg/cloud/aws/ssm/ssm-operations.go
- pkg/kube-aws/ebs-loss/environment/environment.go
- pkg/kube-aws/ebs-loss/types/types.go
- pkg/kube-aws/ec2-terminate-by-id/environment/environment.go
- pkg/kube-aws/ec2-terminate-by-id/types/types.go
- pkg/kube-aws/ec2-terminate-by-tag/environment/environment.go
- pkg/kube-aws/ec2-terminate-by-tag/types/types.go
This PR updates the fail-step and error messages for the following AWS experiment
1. ec2-stop-by-id
2. ec2-stop-by-tag
3. ebs-loss-by-id
4. ebs-loss-by-tag
5. aws-ssm-chaos-by-id
6. aws-ssm-chaos-by-tag
Additionally,
1. Fixes issue with empty IDs provided
**Checklist:**
-   [ ] …
> Chore(Fail-Steps): Updated fail-step and error messages for AWS experiments 

- chaoslib/litmus/azure-disk-loss/lib/azure-disk-loss.go
- chaoslib/litmus/azure-instance-stop/lib/azure-instance-stop.go
- experiments/azure/azure-disk-loss/experiment/azure-disk-loss.go
- experiments/azure/instance-stop/experiment/azure-instance-stop.go
- pkg/azure/disk-loss/environment/environment.go
- pkg/azure/disk-loss/types/types.go
- pkg/azure/instance-stop/environment/environment.go
- pkg/azure/instance-stop/types/types.go
- pkg/cloud/azure/common/common.go
- pkg/cloud/azure/disk/disk-operations.go
- pkg/cloud/azure/disk/disk-status.go
- pkg/cloud/azure/instance/instance-operations.go
- pkg/cloud/azure/instance/instance-status.go
This PR updates the fail-step and error messages for the following Azure experiment
1. azure-instance-stop
2. azure-disk-loss
Additionally,
Fixes issue with empty IDs provided
**Checklist:**
-   [ ] PR messages has …
> Chore(Fail-Steps): Updated fail-step and error messages for Azure experiments

- pkg/cerrors/custom_errors.go
- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
> chore(probe): adding phase to continuous and onchaos modes

- contribute/developer-guide/templates/chaoslib_exec.tmpl
- contribute/developer-guide/templates/chaoslib_helper.tmpl
- contribute/developer-guide/templates/chaoslib_non-k8s.tmpl
- contribute/developer-guide/templates/environment_aws.tmpl
- contribute/developer-guide/templates/environment_azure.tmpl
- contribute/developer-guide/templates/environment_exec.tmpl
- contribute/developer-guide/templates/environment_gcp.tmpl
- contribute/developer-guide/templates/environment_helper.tmpl
- contribute/developer-guide/templates/environment_vmware.tmpl
- contribute/developer-guide/templates/experiment_aws.tmpl
- contribute/developer-guide/templates/experiment_azure.tmpl
- contribute/developer-guide/templates/experiment_custom_resource.tmpl
- contribute/developer-guide/templates/experiment_gcp.tmpl
- contribute/developer-guide/templates/experiment_k8s.tmpl
- contribute/developer-guide/templates/experiment_k8s_deployment.tmpl
- contribute/developer-guide/templates/experiment_vmware.tmpl
- contribute/developer-guide/templates/types_aws.tmpl
- contribute/developer-guide/templates/types_azure.tmpl
- contribute/developer-guide/templates/types_exec.tmpl
- contribute/developer-guide/templates/types_gcp.tmpl
- contribute/developer-guide/templates/types_helper.tmpl
- contribute/developer-guide/templates/types_vmware.tmpl
- pkg/kafka/environment/environment.go
- pkg/kafka/types/types.go
> chore(sdk): adding failstep and lib changes to sdk

- pkg/utils/exec/exec.go
> fix(stderr): adding the fix for cmd.Exec considers log.info as stderr

- pkg/probe/cmdprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/promProbe.go
- pkg/utils/retry/retry.go
> chore(probe-timeout): converting probe timeout in milli seconds

- contribute/developer-guide/templates/chaoslib_exec.tmpl
- contribute/developer-guide/templates/chaoslib_helper.tmpl
- contribute/developer-guide/templates/experiment_aws.tmpl
- contribute/developer-guide/templates/experiment_azure.tmpl
- contribute/developer-guide/templates/experiment_gcp.tmpl
- contribute/developer-guide/templates/experiment_k8s.tmpl
- contribute/developer-guide/templates/types_aws.tmpl
- contribute/developer-guide/templates/types_azure.tmpl
- contribute/developer-guide/templates/types_exec.tmpl
- contribute/developer-guide/templates/types_gcp.tmpl
- contribute/developer-guide/templates/types_helper.tmpl
- contribute/developer-guide/templates/types_vmware.tmpl
- pkg/vmware/vm-poweroff/types/types.go
> chore(sdk): Updating the sdk to latest experiment schema

- pkg/result/chaosresult.go
> fix(probe): ProbeSuccessPercentage should not be 100% if experiment terminated with Error

- pkg/cerrors/custom_errors.go
- pkg/probe/cmdprobe.go
- pkg/probe/comparator/float.go
- pkg/probe/comparator/integer.go
- pkg/probe/comparator/string.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/result/chaosresult.go
- pkg/types/types.go
> Updating probe description and error codes

- pkg/probe/cmdprobe.go
- pkg/probe/comparator/comparator.go
- pkg/probe/comparator/float.go
- pkg/probe/comparator/integer.go
- pkg/probe/comparator/string.go
- pkg/probe/httpprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/types/types.go
> probe comparator logging for all iterations

- pkg/probe/cmdprobe.go
- pkg/probe/comparator/comparator.go
- pkg/probe/comparator/float.go
- pkg/probe/comparator/integer.go
- pkg/probe/comparator/string.go
- pkg/probe/httpprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/types/types.go
Reverts litmuschaos/litmus-go#646
> Revert "probe comparator logging for all iterations"

- .github/security-scan.yml
- .github/workflows/build.yml
> adding security scan workflow

- .github/workflows/security-scan.yml
> fix the security scan github action

- .github/workflows/security-scan.yml
> fix the snyk token name

- .github/workflows/security-scan.yml
> use the official snyk action

- .github/workflows/security-scan.yml
> run workflow on dispatch event and use token from secrets

- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/types/types.go
> chore(onchaos): Busy wait for onchaos mode

- pkg/cerrors/custom_errors.go
- pkg/probe/cmdprobe.go
- pkg/probe/comparator/float.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/types/types.go
- pkg/utils/utils.go
> chore(onchaos): Add busy wait for onchaos and http probe timeout failure

- pkg/utils/common/pods.go
> Add fix to remove the job labels from helper pod

- chaoslib/litmus/network-chaos/helper/netem.go
Fixes: #https://github.com/litmuschaos/litmus/issues/4149
**Checklist:**
> chore(network): fix the destination ips for network experiment for service mesh

- pkg/utils/common/pods.go
> [Cherry-pick] Add fix to remove the job labels from helper pod (#665)

- build/Dockerfile
> fix(dockerfile): Fix the sudo command error

- .github/workflows/release.yml
- Makefile
> fix(action): Fix the github release action

- chaoslib/litmus/network-chaos/helper/netem.go
> Add port blacklisting in the pod-network faults (#673)

- chaoslib/litmus/network-chaos/helper/netem.go
> Add port blacklisting in the pod-network faults

- go.mod
- go.sum
- pkg/utils/common/common_fuzz_test.go
- pkg/utils/common/testdata/fuzz/FuzzRandomInterval/711bbee1d16a50e2
> test: Adding fuzz testing for common util

- chaoslib/litmus/cpu-stress/lib/cpu-stress.go
- chaoslib/litmus/process-kill/lib/process-kill.go
- pkg/machine/common/messages/messages.go
- pkg/machine/cpu/cpu-status.go
- pkg/machine/process/process-status.go
- pkg/probe/cmdprobe.go
- pkg/utils/common/common.go
Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>
**What this PR does / why we need it**: Refactors the feedback messages to reduce repetition of code.
**Checklist:**
> Refactored Feedback Messages Validation

- go.mod
- go.sum
- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/promProbe.go
- pkg/utils/utils.go
> chore(probe): Fix the probe description on failure

- go.mod
- go.sum
- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/promProbe.go
- pkg/utils/utils.go
* chore(probe): Fix the probe description on failure
* chore(probe): Consider http timeout as probe failure
---------
**Checklist:**
-   [ ] E2E run Required for …
> chore(probe): Fix the probe description on failure (#692)

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
> chore(io-stress): Fix the pod-io-stress experiment

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
> chore(stress): Fix the stress faults

- pkg/utils/common/common.go
> fix(logs): Fix the error logs for container-kill fault

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
> fix(container-kill): Fixed the container stop command timeout issue

- bin/experiment/experiment.go
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/corruption/corruption.go
- chaoslib/litmus/network-chaos/lib/duplication/duplication.go
- chaoslib/litmus/network-chaos/lib/latency/latency.go
- chaoslib/litmus/network-chaos/lib/loss/loss.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/network-chaos/lib/rate/rate.go
- experiments/generic/pod-network-rate-limit/README.md
- experiments/generic/pod-network-rate-limit/experiment/pod-network-rate-limit.go
- experiments/generic/pod-network-rate-limit/rbac.yaml
- experiments/generic/pod-network-rate-limit/test/test.yml
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/types/types.go
- pkg/utils/common/common.go
- pkg/utils/common/nodes.go
- pkg/utils/common/pid.go
- pkg/utils/common/pods.go
**What this PR does / why we need it**: adds port filtering for ip/hostnames for network faults, adds pod-network-rate-limit fault
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #759 #760 
**Checklist:**
> feat: adds port filtering for ip/hostnames for network faults, adds pod-network-rate-limit fault

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/docker-service-kill/lib/docker-service-kill.go
- chaoslib/litmus/http-chaos/lib/http-chaos.go
- chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- contribute/developer-guide/templates/chaoslib_helper.tmpl
- pkg/utils/common/nodes.go
**What this PR does / why we need it**: adds common functions for helper pod lifecycle management
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #762 
**Checklist:**
> chore: adds common functions for helper pod lifecycle management
