- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/pod-delete/pod-delete.go
- pkg/environment/environment.go
- Making event recording optional if run via engine only
> feat(events): Making event recording optional if run via engine only

- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/pod-delete/pod-delete.go
- go.mod
- go.sum
- pkg/environment/environment.go
- pkg/events/event.go
- pkg/types/types.go
- Earlier it was not able to patch the events counts concurrently (one by one). Instead, it is patching many counts at a time. 
- It will add the ability to patch the events after each occurrence of events concurrently.
> feat(events): Adding the client-go events

- chaoslib/litmus/cpu_hog/cpu-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- experiments/generic/cpu-hog/cpu-hog-k8s-job.yml
- experiments/generic/cpu-hog/cpu-hog.go
- experiments/generic/pod-delete/pod-delete-k8s-job.yml
This PR includes: 
- Job indentation (pod-delete)
- Do we need `ANSIBLE_STDOUT_CALLBACK` variable here? Removed
- References for pod-delete from cpu-hog experiments.
> refactor(experiments): Refactor litmus go experiments

- chaoslib/litmus/pod_memory_hog/pod-memory-hog.go
- experiments/generic/pod-memory-hog/pod-memory-hog-k8s-job.yml
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- go.sum
- pkg/environment/environment.go
- pkg/types/types.go
**This PR contains:**
- Adding one more resource chaos experiment in the generic experiment of LitmusChaos. The experiment is pod-memory-hog which is used to give a memory spike on a container inside a pod for a certain chaos duration.
- The experiment uses `dd` command to give a chaos spike.
- After the total chaos duration, the command terminates using kill command inside the container.
**Issue:**
fixes: https://github.com/litmuschaos/litmus/issues/1559
**Special notes for your reviewer:**
> feat(experiments): Add pod memory hog experiment

- chaoslib/pumba/network_chaos/pod-network-duplication.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- This PR is for fixing the issues in getting the target container name and summary events.
> bug(fix): Fix for summary event and getting target container name

- chaoslib/pumba/network_chaos/pod-network-duplication.go
- This PR is for removing extra index from the list of pods so that it would not take extra index while running the experiment and results in empty application detail in pod network duplication.
> bug(fix): Remove extra index from the list in pod duplication experiment

- chaoslib/litmus/pod_cpu_hog/pod-cpu-hog.go
- Adding summary event in chaosresult in case of abort
- fixes: #48
> feat(abort): Adding summary event in chaosresult in case of abort

- chaoslib/litmus/pod_cpu_hog/pod-cpu-hog.go
- chaoslib/litmus/pod_memory_hog/pod-memory-hog.go
- contribute/developer-guide/templates/experiment.tmpl
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/result/chaosresult.go
- pkg/types/types.go
- Add the summary events in chaos result for the negative cases of type warning
> update(chaos-result): Add the warning summary event in chaosresult for negative cases

- chaoslib/pumba/container_kill/container-kill.go
- For the negative cases where helper pod failed and it is unable to kill the target container. As we are verifying the restart count after the cleanup of the pod. We can't check the logs oof the helper pod. The cleanup step should present after the verification of the restart count so that we can check the logs of the helper pod for negative cases.
> update(container-kill): refactor the container-kill experiment

- chaoslib/litmus/container_kill/container-kill.go
- chaoslib/litmus/container_kill/helper/crictl.go
- chaoslib/litmus/disk_fill/disk-fill.go
- chaoslib/litmus/pod_cpu_hog/pod-cpu-hog.go
- chaoslib/litmus/pod_delete/pod-delete.go
- chaoslib/litmus/pod_memory_hog/pod-memory-hog.go
- chaoslib/pumba/container_kill/container-kill.go
- chaoslib/pumba/network_chaos/network-chaos.go
- experiments/generic/container-kill/test/test.yml
- experiments/generic/disk-fill/test/test.yml
- experiments/generic/pod-cpu-hog/test/test.yml
- experiments/generic/pod-delete/test/test.yml
- experiments/generic/pod-memory-hog/test/test.yml
- experiments/generic/pod-network-corruption/test/test.yml
- experiments/generic/pod-network-duplication/test/test.yml
- experiments/generic/pod-network-latency/test/test.yml
- experiments/generic/pod-network-loss/test/test.yml
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-delete/environment/environment.go
- pkg/generic/pod-delete/types/types.go
- pkg/generic/pod-memory-hog/environment/environment.go
- pkg/generic/pod-memory-hog/types/types.go
- pkg/utils/common/common.go
- Adding ability to provide the target-pod name as an env in the experiment/engine. If the target-pod name is not defined or not found. it will select a random pod.
> chore(target-pod): Adding ability to pass the target_pod as env

- chaoslib/litmus/container_kill/container-kill.go
- experiments/generic/container-kill/container-kill.go
- go.sum
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- pkg/log/log.go
- Adding all the CRI in the litmus lib.
- The value of container-runtime can be provided in the `CONTAINER_RUNTIME` env. It supports docker, containerd and crio values.
> chore(container-kill): Adding all the CRI in litmus lib

- chaoslib/litmus/pod_cpu_hog/pod-cpu-hog.go
- chaoslib/litmus/pod_memory_hog/pod-memory-hog.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-memory-hog/environment/environment.go
- pkg/generic/pod-memory-hog/types/types.go
- Introduces the CHAOS_INJECT_COMMAND & CHAOS_KILL_COMMAND env vars to control the chaos processes declaratively
> (cmd_fixes)fix: make chaos inject and kill cmds as tunable

- pkg/types/types.go
- Appending the instance-id in the chaos-result name.
```
Name:         engine2-pod-delete-dummay-id
Namespace:    shubham
Labels:       name=engine2-pod-delete-dummay-id
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
Creation Timestamp:  2020-09-04T07:08:16Z
Generation:          2
Resource Version:    2407
Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/shubham/chaosresults/engine2-pod-delete-dummay-id
UID:                 0ed72ec9-5105-457b-bf20-52423d29d908
Spec:
Engine:      engine2
Experiment:  pod-delete
Instance:    dummay-id
Status:
Experimentstatus:
Fail Step:  N/A
Phase:      Completed
Verdict:    Pass
Events:
Type    Reason   Age   From …
```
> chore(chaos-result): appending the instance_id with the chaos-result name

- experiments/cassandra/pod-delete/pod-delete.go
- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-autoscaler/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/cassandra/pod-delete/environment/environment.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-drain/environment/environment.go
- pkg/generic/node-memory-hog/environment/environment.go
- pkg/generic/node-taint/environment/environment.go
- pkg/generic/pod-autoscaler/environment/environment.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-delete/environment/environment.go
- pkg/generic/pod-memory-hog/environment/environment.go
- Passing experiment name from the chaos-runner as env and use the same inside experiment instead of hardcoding it
> chore(exp-name): Passing experiment name from chaos-runner as env

- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- pkg/utils/exec/exec.go
- When chaos-experiment try to eat more memory than the limit value for the target container. Either the target container got restarted or the dd cmd/stress process got killed immediately(block size has the same value as requested m/m to be stressed). In both scenarios, the process won't be available for cleanup. 
- Skipping the cleanup portion, if faced oom-kill(137 error-code) with a warning as it crossed the limit value otherwise it will clean the process.
> fix(pod-memory-hog): Fixing the oom-kill(137) error

- experiments/generic/container-kill/container-kill.go
- experiments/generic/disk-fill/disk-fill.go
- experiments/generic/kubelet-service-kill/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-drain/node-drain.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/node-taint/node-taint.go
- experiments/generic/pod-autoscaler/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/result/chaosresult.go
- pkg/types/types.go
- Adding the following two events in chaosresult
- Awaited verdict in the begg of experiment
- Pass/fail verdict in the end of experiment
- Removing summary event from the chaos-result
> chore(events):removed summary event and add two new events in chaosresult

- build/litmus-go/Dockerfile
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- pkg/generic/kubelet-service-kill/environment/environment.go
- pkg/generic/kubelet-service-kill/types/types.go
- fixes: https://github.com/litmuschaos/litmus/issues/2037
**_This PR is for:_**
- This PR is for merging helper image with the go-runner image for kubelet service kill experiment.
- The `ubuntu:bionic` image used is having an image size of size in 64MB.
> chore(helper): Merge helper image with go-runner for kubelet-service-kill

- chaoslib/pumba/network-chaos/lib/network-chaos.go
- It was appending regex with the same args in each iteration means we were passing cumulative value. It will fail if targeted pod > 1 as regex correspond to higher indexes have cumulative regex( regex expression belongs to other replicas as well).
> fix(pumba-lib): fixing regex for the pumba pod

- build/litmus-go/Dockerfile
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
This PR is for:
- Optimising Dockerfile by removing stress-ng build in dockerfile and removing the multi-stage build.
Stress-ng is directly used in:
- node-cpu-hog
- node-mem-hog
> (chore)dockerfile: Optimize Dockerfile

- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- experiments/generic/container-kill/container-kill.go
- experiments/generic/node-cpu-hog/node-cpu-hog.go
- experiments/generic/node-io-stress/node-io-stress.go
- experiments/generic/node-memory-hog/node-memory-hog.go
- experiments/generic/pod-cpu-hog/pod-cpu-hog.go
- experiments/generic/pod-delete/pod-delete.go
- experiments/generic/pod-io-stress/pod-io-stress.go
- experiments/generic/pod-memory-hog/pod-memory-hog.go
- experiments/generic/pod-network-corruption/pod-network-corruption.go
- experiments/generic/pod-network-duplication/pod-network-duplication.go
- experiments/generic/pod-network-latency/pod-network-latency.go
- experiments/generic/pod-network-loss/pod-network-loss.go
- pkg/utils/common/common.go
- Adding abort support for following experiments:
- container-kill
- network-chaos (pumba)
- node cpu-hog
- node mem hog
- node drain
- node taint
- node io stress
- pod io stress
- pod-delete
> chore(abort): Adding support for abortion in all experiments

- bin/go-runner.go
- build/generate_go_binary
- build/litmus-go/Dockerfile
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- experiments/cassandra/pod-delete/experiment/pod-delete.go
- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
- experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
- experiments/generic/node-drain/experiment/node-drain.go
- experiments/generic/node-io-stress/experiment/node-io-stress.go
- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- experiments/generic/node-taint/experiment/node-taint.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- pkg/log/log.go
- Ruduced the image size to `422MB` from `1900MB`
- fixed: #litmuschaos/litmus/issues/1920
- Introducing name flag in args of experiment CR on the basis of which it will run the corresponding experiment.
- sample experiment CR
```yaml
apiVersion: litmuschaos.io/v1alpha1
description:
message: |
Deletes a pod belonging to a deployment/statefulset/daemonset
kind: ChaosExperiment
metadata:
name: pod-delete
version: 0.1.4
spec:
definition:
permissions:
- apiGroups:
- ""
- "extensions"
- "apps"
- "batch"
- "litmuschaos.io"
resources:
- "daemonsets"
- "deployments"
- "statefulsets"
- "jobs"
- "pods"
- "chaosengines"
- "chaosexperiments"
- "chaosresults"
verbs:
- "*"
image: "shubh214/go-runner:img"
args:
- -c
- ./experiments -name …
```
> chore(reducing-imgsize): Reducing go-runner image size

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/pod-delete/environment/environment.go
- pkg/generic/pod-delete/types/types.go
- pkg/generic/pod-io-stress/environment/environment.go
- pkg/generic/pod-io-stress/types/types.go
- container-kill in docker :heavy_check_mark: 
- container-kill in containerd :heavy_check_mark: 
- disk-fill :heavy_check_mark: 
- network-chaos docker :heavy_check_mark: 
- network chaos containerd :heavy_check_mark: 
- pod-delete :heavy_check_mark: 
- cpu pumba :heavy_check_mark: 
- mm pumba :heavy_check_mark: 
- pod-io-stress :heavy_check_mark:
> chore(sequence): Adding both parallel/serial sequence in all pod-level experiments

- bin/go-runner.go
- build/litmus-go/Dockerfile
- chaoslib/litmus/node-restart/lib/node-restart.go
- experiments/generic/node-restart/README.md
- experiments/generic/node-restart/experiment/node-restart.go
- experiments/generic/node-restart/rbac.yaml
- experiments/generic/node-restart/test/test.yml
- pkg/generic/node-restart/environment/environment.go
- pkg/generic/node-restart/types/types.go
This patch add experiment to restart host via the SSH.
So the example `ChaosEngine` would be:
```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
name: nginx-chaos-restart
spec:
auxiliaryAppInfo: ""
appinfo:
appns: 'kube-system'
applabel: 'tier=control-plane'
appkind: 'deployment'
annotationCheck: 'false'
engineState: 'active'
chaosServiceAccount: chaos-admin
monitoring: false
jobCleanUpPolicy: 'retain'
experiments:
- name: node-restart
spec:
components:
env:
- name: SSH_USER
value: 'docker'
```
Example `ChaosExperiment`:
```yaml
apiVersion: litmuschaos.io/v1alpha1
description:
message: |
Restart node
kind: ChaosExperiment
metadata:
name: node-restart
version: 0.1.21
spec:
definition:
scope: Cluster
permissions:
- apiGroups:
- ""
- "batch"
- "apps"
- "litmuschaos.io" …
```
> Add nodeRestart via SSH experiment

- chaoslib/litmus/node-restart/lib/node-restart.go
- experiments/generic/node-restart/experiment/node-restart.go
- pkg/generic/node-restart/environment/environment.go
This PR aims to fix 2 problems I found while attempting to run the node-restart experiment:
* Running the ssh command in the pod will fail as it attempts to add the target host in the `$HOME/.ssh/known_hosts` file with this error:
`$>oc logs node-restart-fadufq`
`Could not create directory '/.ssh'.`
`Failed to add the host to the list of known hosts (/.ssh/known_hosts).`
The fix consists in passing the flag `-o UserKnownHostsFile=/dev/null` to the ssh command to use `/dev/null` instead.
* Replaced `nodeName` field for a node selector of `anti-affinity` that will avoid scheduling the ephemeral pod that executes the ssh command, in the same target node where the restart will happen. Setting the `nodeName` field will bypass the scheduler and ignore any cordoning applied to the node.
* …
> fix(node-restart): Add node anti affinity and fix ssh known hosts file requirements

- pkg/probe/comparator.go
By adding regex comparator to probe, we can evaluate additional expected
outputs which aren't covered by the existing comparators.
This can be useful in various scenarios, e.g when cmdProbe is used and
the output of the command might be several values that all can be
expected.
The `value` attribute of the `cmdProbe` element must follow the supported golang regex [1]
[1] https://github.com/google/re2/wiki/Syntax
Signed-off-by: Moti Asayag <masayag@redhat.com>
> Add regex comparator to probes

- .github/workflows/guide.md
- .github/workflows/main.yml
This PR includes: 
- Update commands like `set-env` and `add-path` which are deprecated from GitHub actions.
- Update Kind cluster creation action
- Update Chaos Action to the latest version that is `v0.3.0`.
- Make Install and Uninstall as pre & post task in the workflow rather than running for every experiment.
- Set job cleanup policy to `delete`. To save cluster resources. 
- Remove `/merge` command from GitHub actions due to security reasons. 
tested run - https://github.com/uditgaurav/test-litmus-go/runs/1449902688?check_suite_focus=true
> chore(fix): Update /run-e2e CI with latest chaos action and GitHub actions

- pkg/probe/cmdprobe.go
This PR adds more information to the command probe execution failure error message so it is more helpful while debugging the configuration of the probe.
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
> Added error output information to cmdProbe failure error

- chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go
- pkg/generic/pod-autoscaler/environment/environment.go
- pkg/generic/pod-autoscaler/types/types.go
- pkg/probe/k8sprobe.go
This PR enhances the Pod Autoscaler experiment in 3 areas:
* Currently, the existing code only impacts a single deployment/statefulset based on the label selector defined in the engine, but the label selector itself could produce more than 1 result. This change is to follow the behaviour in the `kubelect scale deploy -l <label> --replicas <x>`. The change proposed here captures the name and the current replica count for all the impacted objects and uses this information across the experiment. 
* Adds a new ENV variable `APP_AFFECT_PERC` to specify the percentage of the target applications to be affected by the experiment. This comes in handy when the return query to list all the objects that match the label selector return more than one object. By default it is 100%. The final value is …
> Enhancement for Pod Autoscaler experiment

- pkg/generic/container-kill/environment/environment.go
- pkg/probe/cmdprobe.go
- pkg/types/types.go
Adding a variable to make the probe image pull policy configurable.
Changes are only done in the container kill experiment for testing purpose.
> Adding ProbeImagePullPolicy variable for Container Kill Experiment only

- chaoslib/litmus/node-drain/lib/node-drain.go
This PR guarantees that the potential error generated in the `retry` loop is returned to the caller. In its current form, the error is captured in the `err` variable, but its contents are never returned, instead it always returns a `nil`.
It also adds the `--timeout` flag to the `kubectl` command to `drain` the node, the time being equal to the experiment duration. I noticed in a draining scenario that the `kubelet` CLI failed to complete the operation due to instabilities in the cluster (Pod Disruption Budget of one of the deployments prevented the drain operation to complete, and that kept the experiment running indefinitely). With the timeout, the command will return an error and it will avoid its endless run.
> Add timeout in node-drain operation and ensure error is returned

- pkg/status/application.go
**Problem**
- In infra chaos, When the appLabels are not provided it will check the status of all the pods available in that namespace. There can be the possibility that the residue pods(completed state) of the previous run are available in that namespace which can fail the status check.
**Soln:**
- Ignoring the status check of the chaos pod, while checking application status, if applabel is undefined(not provided).
> chore(logs): skip chaos pod status check for infra chaos

- build/Dockerfile
- experiments/cassandra/pod-delete/experiment/pod-delete.go
- experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
- pkg/kafka/kafka-liveness-cleanup.go
- pkg/kafka/kafka-liveness-stream.go
- Adding chaosresult update and event generation for failure cases in kafka-pod-delete and cassandra-pod-delete experiment.
- Adding unique labels inside kafka liveness pod
> chore(kafka): updating kafka pod failure experiment

- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network_latency/tc/tc.go
If a previous run doesn't manage to clean up all of the state that tc(8)
leaves behind, then "tc qdisc add" will fail.  But, "tc qdisc replace"
will succeed if there is an existing rule or not.
> In pod-network-latency use "replace" rather than "add" with tc.

- Makefile
- build/push
- This PR fixed the broken buildx in CI.
The issue was -- it is not picking the builder created from `buildx` actions that's why I have added a check in Makefile that will verify if the driver is not changed from docker then it will change it. Also, the buildx creates a driver instance which wasn't available on the root repo and hence not accessible from `sudo`.
> Fix docker buildx command in actions CI

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/generic/container-kill/types/types.go
- pkg/generic/disk-fill/types/types.go
- pkg/generic/kubelet-service-kill/types/types.go
- pkg/generic/network-chaos/types/types.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/node-io-stress/types/types.go
- pkg/generic/node-memory-hog/types/types.go
- pkg/generic/node-restart/types/types.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-io-stress/types/types.go
- pkg/generic/pod-memory-hog/types/types.go
- pkg/utils/common/pods.go
- Getting imagePullSecrets from the experiment pod and forward it to the helper pod. Which can be used in case of a private image registry.
> feat(imagePullSecrets): Passing imagePullSecrets into helper pod

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/ebs-loss/lib/ebs-loss.go
- chaoslib/litmus/ec2-terminate/lib/ec2-terminate.go
- chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-drain/lib/node-drain.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/node-taint/lib/node-taint.go
- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- Adding OnChaos mode inside probe in all the experiments. 
- OnChaos mode runs the probes during chaos duration and validates the results continuosuly.
> feat(probe): Adding onchaos mode in all experiments

- experiments/cassandra/pod-delete/experiment/pod-delete.go
- experiments/generic/container-kill/experiment/container-kill.go
- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
- experiments/generic/pod-delete/experiment/pod-delete.go
- experiments/generic/pod-io-stress/experiment/pod-io-stress.go
- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
- experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
- experiments/generic/pod-network-latency/experiment/pod-network-latency.go
- experiments/generic/pod-network-loss/experiment/pod-network-loss.go
- pkg/generic/pod-autoscaler/environment/environment.go
- pkg/status/application.go
- pkg/utils/annotation/annotation.go
- pkg/utils/common/pods.go
- If the annotationCheck is true, It will check the status of the annotated pod only in pre and post chaos checks.
- If the annotationCheck is false. It will check the status of all the pods with matching labels
NOTE: Created a separate category for annotation to avoid the import cycle
> feat(status): Checking status of annotated applications only, if annotationCheck is true

- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- Adding chaos revert steps inside network-chaos
- shifting abort event creation from helper pod to the experiment pod
> feat(abort): shifting chaosengine updation & event creation to experiment pod from helper

- pkg/status/application.go
- skip the AUTStatus check if appinfo is not provided.
- This is useful for the node level chaos where applnfo is optional.
> chore(aut-check): skip autStatus check if appinfo not provided

- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/pumba/network-chaos/lib/corruption/corruption.go
- chaoslib/pumba/network-chaos/lib/duplication/duplication.go
- chaoslib/pumba/network-chaos/lib/latency/latency.go
- chaoslib/pumba/network-chaos/lib/loss/loss.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- Handling the unknown destination hosts in the network chaos experiments. If all the provided hosts are invalid/unknown then failed the experiment. 
- If any subset of destination hosts are known then inject the chaos in those hosts.
> chore(n/w-chaos): Handling the unknown destination hosts

- chaoslib/litmus/container-kill/helper/container-kill.go
- Adding the signal option for the containerd and crio runtimes
- It supports `SIGTERM` and `SIGKILL` signals only
> chore(signal): Adding signal for the crio/containerd runtime

- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
With this PR the init container for changing the permissions of the container runtime socket is removed when using litmus-lib. 
As per discussion with @ksatchit, the init container is only necessary for pumba-lib.
> Remove init container for changing permission of the container runtime socket

- chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- chaoslib/powerfulseal/pod-delete/lib/pod-delete.go
- pkg/cassandra/pod-delete/environment/environment.go
- pkg/generic/pod-delete/environment/environment.go
- pkg/generic/pod-delete/types/types.go
- pkg/kafka/environment/environment.go
- pkg/types/types.go
- pkg/utils/common/common.go
- Adding randomness interval inside pod-delete experiment
- It accepts a lower and an upper bound for the chaos-interval separated by hyphens `-`. If only a single value is provided i.e `10` then it will consider the given value as upper bound and 0 as lower bound.
- It will wait for the random time interval in each iteration of the chaos
> feat(randomness): Adding randomness interval inside pod-delete experiment

- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- pkg/generic/pod-cpu-hog/environment/environment.go
- pkg/generic/pod-cpu-hog/types/types.go
- pkg/generic/pod-memory-hog/environment/environment.go
- pkg/generic/pod-memory-hog/types/types.go
- Adds an additional environment variable "STRESS_IMAGE" for use in pumba lib - with default pointing to `alexeiled/stress-ng:latest-ubuntu`
- This will help users of pumba lib running with private image registries to define their own version of the stress-image. 
> (enhancement)stress-image: add env for stress-image used in pumba lib

- chaoslib/litmus/disk-fill/helper/disk-fill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- experiments/generic/disk-fill/test/test.yml
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/disk-fill/types/types.go
- Adding Block size as tunable by ENV in disk-fill. The env is `BLOCK_SIZE`. The unit is always `K`.
> chore(disk-fill): Adding Block size as tunable in disk-fill

- experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
- pkg/utils/exec/exec.go
- Before exec inside target container, validating that the status of target pod and container. If the pod is in running state and the container is ready then only exec and run the command else error it out.
> chore(exec): execing inside target pod only if it is in ready state

- chaoslib/litmus/pod-cpu-hog/lib/pod-cpu-hog.go
- chaoslib/litmus/pod-memory-hog/lib/pod-memory-hog.go
- pkg/utils/exec/exec.go
-  fixing 137 error in cpu & memory chaos. When we are using `kill -9` command to kill the process then it terminates the process with 137 error which was considered an error earlier.
> chore(stress): fixing 137 error in cpu & memory chaos

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
- pkg/status/application.go
-  Earlier for the small chaos duration helper pod completed within few seconds so helper pod status check was not able to detect and failed. 
- updating the helper status check logic to consider the pod phase as succeed as well
> chore(helper): updating the helper pod status check

- chaoslib/litmus/ec2-terminate-by-id/lib/ec2-terminate-by-id.go
- chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
- experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
- pkg/cloud/aws/ec2-operations.go
- pkg/kube-aws/ec2-terminate-by-tag/types/types.go
- Update the pre and post chaos check for ec2-terminate using tags.
- `pre-chaos`: Will check if any running instance found filtered from given instance tag. If no instance found it will fail. So it will now manage the case where the filtered set of instances are both running and non-running instances.
- `post-chaos`: Status check of the target instance under chaos (IUC). It will fail if the target instance is not in running state post chaos.
> Chore(EC2-checks): Update the ec2 terminate with tags experiment to target only running instances

- build/Dockerfile
- Update Dockerfile to take binaries from test-tool release artefact
**Checklist:**
-   [ ] E2E run Required for the …
> Chore(Dockerfile): Update Dockerfile to take binaries from test-tool release artefact

- pkg/result/chaosresult.go
- pkg/utils/annotation/annotation.go
- Earlier, if the parent resource labels are not provided then it was failing to list the parent resources even if annotationCheck is false.
- Marking the parent resource labels as an optional field if annotationCheck is false but it is mandatory if annoationCheck is provided as true.
**Checklist:**
-   [ ] PR messages has breaking changes related …
> feat(annotation): skipping parent resources listing, if annotationCheck is false

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- pkg/generic/pod-cpu-hog-exec/environment/environment.go
- pkg/generic/pod-cpu-hog-exec/types/types.go
- pkg/generic/pod-memory-hog-exec/environment/environment.go
- pkg/generic/pod-memory-hog-exec/types/types.go
- pkg/generic/stress-chaos/environment/environment.go
- pkg/kube-aws/ebs-loss/types/types.go
- Remove extra privileges from helper pod for stress chaos
_For IO Stress:_
- Have removed the `--cpu` flag in the stress-ng as it is not specific to the exp. It is now an optional value if the user has provided some CPU then it will take otherwise it will skip.
- In place of waiting for 10s of grace period for stress-ng to get completed after the `--timeout` value is completed. We have increased it to `30s` for some edge cases.
NOTE: This is a different grace period not for helper completion but for stress-ng completion after `--timeout` in stress-ng command. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets …
> Chore(stress-chaos): Remove extra previlages and update io stressors and timeout

- Makefile
- build/push
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>
This PR introduces an option to specify a container registry where litmus images will be pushed after the build. The registry is specified by env variable `DOCKER_REGISTRY`. This PR also removes `docker login` command from `push` script. I think all users should do this out of this script.
This change might be useful for users who build their own images and it adds an option to push images to multiple container registries during automated builds.
**Checklist:**
-   [ ] PR messages has breaking changes related …
> Add option to change default container registry for image build

- chaoslib/litmus/azure-instance-stop/lib/azure-instance-stop.go
- go.sum
- pkg/azure/instance-stop/environment/environment.go
- pkg/azure/instance-stop/types/types.go
- pkg/cloud/azure/azure-instance-status.go
- pkg/cloud/azure/azure-operations.go
Signed-off-by: Akash Shrivastava <akash@chaosnative.com>
This PR adds the support for virtual machine scale sets in the azure instance stop experiment. Currently the instance stop experiment only works for VM instances, with this PR we can run the experiment for AKS nodes as well.
**Checklist:**
-   [ ] Labelled this PR & related issue with …
> Chore(Azure): Azure Instance Stop experiment (support for: virtual machine scale sets)

- experiments/generic/node-memory-hog/experiment/node-memory-hog.go
- pkg/utils/common/nodes.go
**What this PR does / why we need it**
1. Adds auxiliary application check functionality to the node-memory-hog experiment
2. Fixes the functionality of specifying multiple target nodes as comma-separated-values in for `node-cpu-hog`, `node-memory-hog`, and `node-io-stress` experiment.
**Which issue this PR fixes**
fixes #423
> Auxiliary Application Check for node-memory-hog Experiment and Multiple Target Node Functionality Fix for three Node-Level Experiments

- chaoslib/litmus/pod-cpu-hog-exec/lib/pod-cpu-hog-exec.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/litmus/pod-memory-hog-exec/lib/pod-memory-hog-exec.go
- experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
- pkg/generic/pod-cpu-hog-exec/environment/environment.go
- pkg/generic/pod-memory-hog-exec/environment/environment.go
- pkg/utils/common/pods.go
This PR fixes minor issues in pod level experiments
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #414 #413 
Other issues fixed: 
1. pod-memory-hog-exec and pod-cpu-hog-exec was not working for serial sequence
2. pod-dns chaos experiments was not working for serial sequence
**Checklist:**
-   [x] Fixes #414 #413 
-   [ ] PR messages has upgrade related …
> Pod experiment fixes

- pkg/result/chaosresult.go
- pkg/status/application.go
Fix:
- Experiment stuck for 3mins or more if helper pods failed/error. It should failed experiment immediately if helper pods fail. 
- remove the label `name: result-name` from chaosresult as it may exceed the k8s label length limit(63 char) if the result name is long
**Checklist:**
-   [ ] Fixes #411 
-   [ ] Labelled …
> feat(helper-status): fix helper status timeout when helper pod failed

- chaoslib/litmus/pod-cpu-hog-exec/lib/pod-cpu-hog-exec.go
- chaoslib/litmus/pod-memory-hog-exec/lib/pod-memory-hog-exec.go
- Handle the abort signal for the pod-cpu-hog-exec and pod-memory-hog-exec experiments. 
**Checklist:**
-   [ ] Commit has integration …
> feat(exec-chaos): handle the abort signal

- chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
- chaoslib/litmus/pod-delete/lib/pod-delete.go
- pkg/cassandra/pod-delete/environment/environment.go
- pkg/generic/container-kill/environment/environment.go
- pkg/generic/disk-fill/environment/environment.go
- pkg/generic/network-chaos/environment/environment.go
- pkg/generic/pod-cpu-hog-exec/environment/environment.go
- pkg/generic/pod-delete/environment/environment.go
- pkg/generic/pod-dns-chaos/environment/environment.go
- pkg/generic/pod-memory-hog-exec/environment/environment.go
- pkg/generic/stress-chaos/environment/environment.go
- pkg/kafka/environment/environment.go
- pkg/utils/common/pods.go
In pod-delete experiments, the parent name is used to patch inside chaosresult along with chaosStatus. The derivation of parent name is limited to pod-delete experiment so deriving the parent name for pod-delete experiment only. Removed the step from the other experiments.
**Checklist:**
- …
> feat(experiment): derive parent name in pod-delete only

- chaoslib/pumba/container-kill/lib/container-kill.go
- chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
- chaoslib/pumba/memory-chaos/lib/memory-chaos.go
- chaoslib/pumba/network-chaos/lib/corruption/corruption.go
- chaoslib/pumba/network-chaos/lib/duplication/duplication.go
- chaoslib/pumba/network-chaos/lib/latency/latency.go
- chaoslib/pumba/network-chaos/lib/loss/loss.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>
Its remove the huge security issue that do chmod 777 on your host docker sock
Is the read/write mount no enought ?
Its give the DOCKER_HOST variable to pumba ( iam using docker but my sock is not default path)
https://github.com/litmuschaos/litmus/issues/3147
**Checklist:**
-   [x] Fixes https://github.com/litmuschaos/litmus/issues/3147
-   [ ] PR messages has breaking …
> Add DockerSocket to network experiments && remove chmod 777

- pkg/utils/common/pods.go
Removing `job-name` label from the helper pod as chaos-runner is using  `job-name` label to watch experiment pod/job. 
**Checklist:**
-   [ …
> fix(helper): removing job-name label from the helper pod

- chaoslib/litmus/node-drain/lib/node-drain.go
- pkg/status/nodes.go
Signed-off-by: Andrew Hu <andrew.hu@hcl.com>
In the node drain experiment, the node will be deleted after draining the node if we enable the autoscaling for the node pool on the cloud provider. And it will cause an error when litmus-go trying to uncordon the non exist node. In this PR, it will check if the node still exists before uncordon the node.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/litmuschaos/litmus/issues/3350
**Checklist:**
-   [ ] Fixes #3350
-   [ …
> Skip uncordon the not exist node after node drain experiment

- contribute/developer-guide/templates/experiment.tmpl
This PR introduces changes to the fail step messages in experiment template of litmus-SDK to follow the new convention
Signed-off-by: Akash Shrivastava <akash@chaosnative.com>
**Checklist:**
-   [ ] …
> FailStep message update in litmus-sdk templates

- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- pkg/generic/node-cpu-hog/environment/environment.go
- pkg/generic/node-cpu-hog/types/types.go
- pkg/generic/stress-chaos/environment/environment.go
- pkg/generic/stress-chaos/types/types.go
- Add capability to run CPU chaos with the percentage of CPU cores. The enhancement will be added to pod-cpu-hog and node-cpu-hog experiments.
- This makes use of `--cpu-load` flag in the stress-ng command. The details are here:
```
-l P, --cpu-load P
load  CPU  with  P  percent  loading for the CPU stress workers. 0 is effectively a
sleep (no load) and 100 is full loading.  The loading loop is broken  into  compute
time (load%) and sleep time (100% - load%). Accuracy depends on the overall load of
the processor and the responsiveness of the scheduler, so the actual  load  may  be
different  from  the desired load.  Note that the number of bogo CPU operations may
not be linearly scaled with the load …
```
> Chore(stress-chaos): Run CPU chaos with percentage of cpu cores

- build/Dockerfile
Fixing alpine CVEs by upgrading the version
Docker scan
```
Organization:      imrajdas
Package manager:   apk
Project name:      docker-image|litmuschaos/litmus-go
Docker image:      litmuschaos/litmus-go:ci
Platform:          linux/amd64
Base image:        alpine:3.12.0
Licenses:          enabled
Tested 23 dependencies for known issues, found 40 issues.
Base Image     Vulnerabilities  Severity
alpine:3.12.0  22               2 critical, 14 high, 5 medium, 1 low
Recommendations for base image upgrade:
Minor upgrades
Base Image   Vulnerabilities  Severity
alpine:3.14  0                0 critical, 0 high, 0 medium, 0 low
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that …
> Fixing alpine's 40 CVEs by upgrading the version

- .github/workflows/build.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- .github/workflows/run-e2e-on-pr-commits.yml
- build/Dockerfile
- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/powerfulseal/pod-delete/lib/pod-delete.go
- go.mod
- go.sum
- pkg/status/nodes.go
- Remove openebs pkgs for retry and use litmus utils instead
- Update go.mod pkgs
- Update go version to 1.17
**Checklist:**
-   [ ] E2E run Required for the …
> Chore(vulnerability): Remove openebs retry module and update pkgs

- .github/workflows/build.yml
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- go.sum
- The current cgroup in the stress chaos experiment only supports version v1. This PR will add support for the containers that are running with cgroup version v2.
- Get more details here about cgroup version 2- https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html
- Now by default for running stress chaos the experiment looks for containers with cgroup of version v1 but has a check to support v2 as well.
**Checklist:**
-   [ ] PR messages has document related …
> Chore(cgroup): Add support for cgroup version2 in stress-chaos experiment

- build/Dockerfile
- This PR changes the directory of the SSM file - it is done so because now the base image is having a default directory of /litmus so we don't need to copy the SSM docs now in /litmus otherwise it will result in the directory structure as follow: /litmus/litmus/SSM-Chaos 
- The changes are according to the default SSM values and docs.
**Checklist:**
-   [ ] …
> Chore(ssm): Update the ssm file path in the Dockerfile

- chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
Signed-off-by: Jimmy Zhang <zhang.artur@gmail.com>
Add --stress-image for stressArgs when calling pumba lib
Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #
fixes #3610
https://github.com/litmuschaos/litmus/issues/3610 
**Checklist:** …
> Add --stress-image for stressArgs for pumba lib

- chaoslib/litmus/node-drain/lib/node-drain.go
Signed-off-by: Akash Shrivastava <as86414@gmail.com>
After draining the node, if the app and aux-app status check failed, the node wasn't being uncordoned as part of the revert. This PR fixes that issue by adding the uncordon node step if the app status check fails.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #520
**Checklist:**
-   [x] Fixes #520
-   [ ] PR messages has upgrade related …
> Chore[Fix]: Node uncordon when app status check failed inside lib

- pkg/status/application.go
Signed-off-by: Gonzalo Reyero Ferreras <greyerof@redhat.com>
Return statement missing on function AnnotatedApplicationsStatusCheck(). Otherwise, the function will do the `return nil` (line 103), making the Try function to (wrongly) succeed.
**Checklist:**
-   [ ] Labelled this PR & related issue with …
> Add missing return to AnnotatedApplicationsStatusCheck

- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-network-partition/lib/network-policy.go
- chaoslib/pumba/network-chaos/lib/network-chaos.go
- pkg/utils/common/common.go
> Deriving podIps of the pods for k8s service if target pod has serviceMesh sidecar

- pkg/result/chaosresult.go
- pkg/status/application.go
PR to fix
- chaosresult update conflicts for abort scenarios
- remove the duplicate targets inside the chaosresult
- fix experiment to failed if helper is evicted or manually deleted
**Issue:** 
In abort scenarios - helper pod keep annotating the chaos-result for  targets and their revert status. At the same time experiment pod is updating the chaosresult for abort in parallel
Experiment pod get and update the chaosresult  but in the mean-time helper pod updates the chaosresult for annotations, which cause the update function to fail.
**Checklist:**
-   [ …
> fix(abort): fixing chaosresult annotation conflict while updating chaosresult for abort scenarios

- go.mod
- go.sum
- pkg/probe/probe.go
- pkg/result/chaosresult.go
- pkg/types/types.go
**Probe Statuses**
```yaml
{
"probeStatuses": [
{
"mode": "SOT",
"name": "probe1",
"status": {
"description": "Probe didn't met the passing criteria",
"verdict": "Failed"
},
"type": "httpProbe"
},
{
"mode": "Continuous",
"name": "probe2",
"status": {
"description": "either probe is not executed or not evaluated",
"verdict": "N/A"
},
"type": "httpProbe"
}
]
}
```
**Checklist:**
-   [ ] Labelled this PR & related …
> fix(probe): Converting probeStatus to enum and add mode and description

- pkg/probe/cmdprobe.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/result/chaosresult.go
- pkg/types/types.go
1. Handled edge mode, when probe is failed in prechaos phase but it is passed in postchaos phase and stopOnfailure set to false
2. Fixed the probeSuccessPercentage > 100 issue (  litmuschaos/litmus#3573 )
3. Fixed the onchaos probe to run only for the chaos duration interval
**Checklist:**
-   [ ] PR messages has breaking changes related …
> fix(probe): Resiliency Score reaches more than 100 % with Probe failure

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
For long chaos duration, if we abort the experiment. It doesn't revert the chaos immediately. It waits for the chaos duration to over before reverting chaos
It kills the parent process as part of revert but stress-ng orphaned child keep running so stress process persist in target application
Launch the nsutil process with groupId. All the child processed can be deleted using this groupId
**Checklist:**
-   [ ] …
> fix(stress): kill the stress process for abort

- pkg/generic/network-chaos/environment/environment.go
Signed -off-by:  Ashis kumar Naik <ashishami2002@gmail.com>
*added the missing JITTER ENV for the network latency experiment to the experiment structure
*updated the default value of Network Latency to 2000 ms
**Checklist:**
- …
> Add missing Jitter ENV input for Pod Network Chaos experiments (#563)

- go.mod
- go.sum
- pkg/probe/httpprobe.go
> chore(httpProbe): Remove responseTimeout field, use the global probeTimeout field instead

- chaoslib/litmus/http-chaos/helper/http-helper.go
- chaoslib/litmus/http-chaos/lib/http-chaos.go
> chore(httpchaos): Adding support for serviceMesh

- chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go
Signed-off-by: Ashis Kumar Naik <ashishami2002@gmail.com>
**What this PR does / why we need it**:  *Removed the redundant sanity checks in GCP VM instance stop experiment in chaoslib which were originally also defined in the steady state check function for the experiment.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #554 
**Checklist:**
-   [ ] PR messages has …
> Remove Redundant Steady-State Checks in GCP VM Instance Stop experint (#554)

- experiments/generic/disk-fill/experiment/disk-fill.go
- experiments/generic/pod-delete/experiment/pod-delete.go
For the `pod-delete` and `disk-fill` experiments, the result of `GetStatusMessage` wasn't assigned to the `msg` variable for updating at some places. This PR will fix that.
**Checklist:**
-   [ ] PR messages have breaking changes related information
-   [ ] PR messages has …
> Chore(Fix): `msg` variable assigned return value of `GetStatusMessage`

- pkg/probe/cmdprobe.go
- pkg/probe/comparator/float.go
- pkg/probe/comparator/integer.go
- pkg/probe/comparator/string.go
- pkg/probe/httpprobe.go
- pkg/probe/k8sprobe.go
- pkg/probe/probe.go
- pkg/probe/promProbe.go
- pkg/result/chaosresult.go
```yaml
- Probe responded with a invalid output. Actual value: 200 is not greater than Expected value: 400
- The URL https://litmuschaos.io did respond with correct status code. Actual and Expected status codes are 200 and 200 respectively
- Get "https://litmuschaos.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
```yaml
- Probe responded with a valid output. Actual and Expected values are ‘shubham’ and ‘shubham’ respectively
- Probe responded with a invalid output. Actual value: shubham doesn't matched with any of the Expected values: [hello world]
- Either probe is not executed or not evaluated
```
```yaml
-  Probe is successfully performed the …
```
> chore(probe): Adding the root cause into probe description

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/docker-service-kill/lib/docker-service-kill.go
- chaoslib/litmus/http-chaos/lib/http-chaos.go
- chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
- chaoslib/litmus/node-io-stress/lib/node-io-stress.go
- chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
- chaoslib/litmus/node-restart/lib/node-restart.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/litmus/pod-network-partition/lib/pod-network-partition.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- contribute/developer-guide/templates/chaoslib_helper.tmpl
- pkg/cassandra/liveness.go
- pkg/kafka/kafka-liveness-stream.go
- pkg/probe/cmdprobe.go
- pkg/types/types.go
- pkg/utils/common/common.go
- pkg/utils/stringutils/string.go
> chore(parallel): add support to create unique runid for same timestamp

- experiments/vmware/vm-poweroff/experiment/vm-poweroff.go
- pkg/cloud/vmware/vm-tag.go
- pkg/vmware/vm-poweroff/environment/environment.go
- pkg/vmware/vm-poweroff/types/types.go
This PR adds support to filter Vmware VM instances by tag in the `vmware-poweroff` experiment. 
Note: Only one tag is supported.
**Checklist:** …
> Added filtering VM instances by tag

- pkg/probe/httpprobe.go
- pkg/probe/probe.go
**What this PR does / why we need it**: Updates http probe wait duration to ms
**Checklist:**
> chore(probe): Updates http probe wait duration to ms

- chaoslib/litmus/node-drain/lib/node-drain.go
This PR add a call to try to revert the chaos in the node-drain experiments when the drain node is failing. For example, this can happens when the node take too long to drain the node and the the timeout is reach and without trying to revert the chaos the nodes stay cordoned. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #667
Didn't add a check if the node was really cordon before trying an uncordon since uncordon a non cordoned node to not create a error when doing it with kubectl.
**Checklist:**
-   [ ] Labelled this …
> Revert chaos when error during drain for node-drain experiments

- pkg/utils/common/pods.go
The App Kind specified by the user shall be taken into consideration when identifying target pods for the experiment so the experiment is carried out on pods that are consistent with the users inputs
Fixes #679 
**Checklist:**
-   [X] Fixes #<issue number>
- …
> Fix consider appKind when filtering target pods

- chaoslib/litmus/network-chaos/lib/network-chaos.go
Ignore pods with no IP address, this can be the case if pod is still in pending state. This will help prevent following error when injecting network fault:
``` json
{"source":"pod-network-corruption-helper-nrb8b","errorCode":"HELPER_ERROR","phase":"ChaosInject","reason":"failed to create destination ips match filters: Illegal \"match\"\n"}
```
I was considering getting pod IPs from SVC endpoints; however, the RBAC permissions for Chaos Helper pods don't have access to list endpoints, which would likely become a breaking change. We can consider moving to that approach when we plan to rollout the next major version.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR …
> fix: accomodate for pending pods with no IP address in network fault

- go.mod
- pkg/utils/common/common.go
- pkg/utils/common/common_fuzz_test.go
- pkg/utils/common/testdata/fuzz/FuzzRandomInterval/711bbee1d16a50e2
> test: Adding fuzz testing for common util

- chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
I've updated the points mentioned in that PR. 
https://github.com/litmuschaos/litmus-go/pull/687
**Checklist:**
> chore: minor code enhancement

- chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
- experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
- experiments/kube-aws/ec2-terminate-by-tag/test/test.yml
- pkg/kube-aws/ec2-terminate-by-tag/environment/environment.go
- pkg/kube-aws/ec2-terminate-by-tag/types/types.go
**Proposed changes:**
Related issue https://github.com/litmuschaos/litmus/issues/4807#issuecomment-2271358440
This PR fixes an issue where the [ec2-stop-by-tag](https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-stop-by-tag/) experiment fails to target the intended EC2 instance.
The [ec2-stop-by-tag](https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-stop-by-tag/) experiment encounters a `TARGET_SELECTION_ERROR` due to an incorrect retrieval of the `EC2_INSTANCE_TAG` environment variable.
```
Fault Summary:
TARGET_SELECTION_ERROR
{"errorCode":"TARGET_SELECTION_ERROR","phase":"PreChaos","reason":"failed to get the instance tag, invalid instance tag","target":"{EC2 Instance Tag: , Region: ap-northeast-2}"}
```
By correctly renaming the environment variable …
> Rename env to EC2_INSTANCE_TAG

- .github/workflows/build.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- build/Dockerfile
> (chore): Fix the build, push, and release pipelines

- chaoslib/litmus/network-chaos/helper/netem.go
As of now, `err` is not being used in https://github.com/litmuschaos/litmus-go/blob/master/chaoslib/litmus/network-chaos/helper/netem.go#L133C3-L135C4  instead of `revertErr`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #720 
**Checklist:**
-   [X] Fixes #720
-   [ ] Commit …
> use revertErr instead of err

- build/Dockerfile
This PR adds `openssh-clients` to the list of generally useful packages which lets you use `ssh`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #727
**Checklist:**
-   [X] Fixes #727 
> add openssh-clients to dockerfile

- chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
- pkg/load/k6-loadgen/environment/environment.go
- pkg/load/k6-loadgen/types/types.go
k6 supports exporting results output in real-time.
This PR implements exporting results output to the OTEL collector followed this [instruction](https://grafana.com/docs/k6/latest/results-output/real-time/opentelemetry
).
Here's a result. k6 [automatically converts all metric types](https://grafana.com/docs/k6/latest/results-output/real-time/opentelemetry/#metrics-mapping) to an equivalent OTEL metric type. So we don't have to do anything.
Also, I added tags named `trace_id` so we can filter by current trace context.
dependencies: https://github.com/litmuschaos/litmus-go/pull/725
fyi: [config format](https://grafana.com/docs/k6/latest/get-started/results-output/)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> feat: export k6 results output to the OTEL collector

- bin/helper/helper.go
- chaoslib/litmus/container-kill/helper/container-kill.go
- chaoslib/litmus/disk-fill/helper/disk-fill.go
- chaoslib/litmus/http-chaos/helper/http-helper.go
- chaoslib/litmus/network-chaos/helper/netem.go
- chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
This PR is a follow-up to PR #706 and implements phase 2 of issue #709.
It enables tracing for previously untracked helper-using experiments: `container-kill`, `disk-fill`, `dns-chaos`, `stress-chaos`, `network-chaos`, `http-chaos`.
Here is the result image below for the details.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #709 
**Checklist:**
-   [ ] Labelled this PR & related issue with …
> Propagate trace context to helper pods

- chaoslib/litmus/stress-chaos/helper/stress-helper.go
> (chore): fix the go fmt of the files

- chaoslib/litmus/container-kill/helper/container-kill.go
Should the container-kill experiment fail with an error, the error message is not logged and it is not included included in the fault summary of the experiment run. This would happen if the command used to kill the container returns an exit code other than 0. It makes it hard to troubleshoot container-kill, if it isn't working as intended.
The problem is that text added to the error the description is taken from the stdout of the command rather than stderr. 
To fix this I have used the common.RunCLICommand function to execute the command. This will use the output from stderr to be included the error message instead of stdout.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that …
> Include error message from stderr if container-kill fails (#740)

- bin/experiment/experiment.go
- chaoslib/litmus/rds-instance-stop/lib/rds-instance-stop.go
- experiments/kube-aws/rds-instance-stop/README.md
- experiments/kube-aws/rds-instance-stop/experiment/rds-instance-stop.go
- experiments/kube-aws/rds-instance-stop/rbac.yaml
- experiments/kube-aws/rds-instance-stop/test/test.yml
- pkg/cloud/aws/rds/rds-instance-status.go
- pkg/cloud/aws/rds/rds-operations.go
- pkg/kube-aws/rds-instance-stop/environment/environment.go
- pkg/kube-aws/rds-instance-stop/types/types.go
I have implemented the rds-instance-stop chaos fault in this PR based on the [proposal](https://github.com/litmuschaos/litmus/pull/4860).
Please see also https://github.com/litmuschaos/chaos-charts/pull/635
cc. @namkyu1999 
**Checklist:**
-   [ ] PR messages has upgrade related …
> feat: Add a rds-instance-stop chaos fault

- pkg/utils/retry/retry.go
- pkg/utils/retry/retry_test.go
This PR adds unit tests for the `retry` package (`retry.go`) under the `utils` directory.  
It improves test coverage by validating:
- Retry success and failure flows
- Timeouts
- Special case: breaking on `"container is in terminated state"`
- Nil action handling
It also modifies `Try()` to use `.Error() == "..."` instead of pointer comparison, making it more testable and idiomatic.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>` format)*:  
Fixes #752 
(*Update once issue is created*)
- All tests are table-driven and isolated
- 100% coverage for `retry.go` can be verified using `go test -cover`
- Let me know if you'd prefer a separate PR for the `.Error()` check improvement
--- …
> test: add unit tests for retry.go in pkg/utils folder

- pkg/utils/exec/exec.go
- pkg/utils/exec/exec_test.go
This PR adds unit tests for two utility functions in the `exec.go` file inside the `utils` package:
- `SetExecCommandAttributes`
- `checkPodStatus`
These are pure functions and testable without external dependencies.  
This contribution is part of a larger effort to improve test coverage across the `utils` package.
> ⚠️ Note: This PR provides **partial coverage** (currently ~33%) since the `Exec()` function depends on Kubernetes APIs and remote SPDY execution, which would require more advanced mocking or integration setup. That work can be done in a follow-up PR.
---
Fixes #752 
---
- Tests are written with table-driven and edge case validation
- Maintainers are welcome to suggest how to approach testing `Exec()` …
> test: add unit tests for exec.go file in pkg/utils folder

- chaoslib/litmus/container-kill/lib/container-kill.go
- chaoslib/litmus/disk-fill/lib/disk-fill.go
- chaoslib/litmus/http-chaos/lib/http-chaos.go
- chaoslib/litmus/network-chaos/lib/network-chaos.go
- chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
- chaoslib/litmus/stress-chaos/helper/stress-helper.go
- chaoslib/litmus/stress-chaos/lib/stress-chaos.go
- contribute/developer-guide/templates/chaoslib_helper.tmpl
- pkg/clients/k8s.go
- pkg/utils/common/common.go
- pkg/utils/common/nodes.go
- pkg/utils/common/pid.go
- pkg/utils/common/pods.go
- pkg/utils/utils.go
This PR implements multi-container targeting support for stress chaos experiments (pod-cpu-stress, pod-memory-stress, pod-io-stress), allowing chaos injection across multiple containers within the same pod simultaneously.
Previously, stress chaos experiments could only target a single container per pod, limiting their effectiveness in modern containerized environments where pods commonly run multiple containers (main application + sidecars + proxies + monitoring containers).
- More realistic fault injection scenarios
- Better coverage for modern containerized applications
- Support for service mesh and sidecar patterns
- Comprehensive error handling and rollback
- Better process lifecycle management
- Enhanced OOM detection capabilities
- Centralized helper pod management
- Reduced code …
> feat: Adds multi container support for pod stress faults
